### ISSUE TITLE
Issue running locally

### ISSUE THREAD

**Issue by stefanpenner** [codeclimate/codeclimate#1]
I suspect this is an issue on my end, but i figure I would post here, maybe someone else has an idea.

```
docker pull codeclimate/codeclimate:latest
FATA[0000] Post http:///var/run/docker.sock/v1.18/images/create?fromImage=codeclimate%2Fcodeclimate%3Alatest: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
make: *** [install] Error 1
```

**Comment by kevinSuttle** [comment]
It's a Docker issue. If you're on Mac, check that boot2docker is installed and running (`boot2docker up`).

**Comment by pbrisbin** [comment]
We've seen this error happen if you've not set the environment variables needed by `boot2docker`.

I *believe* the fix is to put something like `eval $(boot2docker shellinit)` in your shell startup file, but I'm not 100% sure (I'm a Linux user).

**Comment by pbrisbin** [comment]
Or write the output of `boot2docker shellinit` into your startup file directly (to avoid the `eval` on every new terminal)

**Comment by kevinSuttle** [comment]
I set it in my config.fish file:

```
set -x DOCKER_HOST tcp://192.168.59.103:2376
set -x DOCKER_CERT_PATH /Users/kevinsuttle/.boot2docker/certs/boot2docker-vm
set -x DOCKER_TLS_VERIFY 1
```

So, substitute bashrc or zshrc

**Comment by pbrisbin** [comment]
@kevinSuttle sorry, was you're issue (#2) fixed by `boot2docker up`, or still failing with the same error?

**Comment by kevinSuttle** [comment]
Fixed by it.

**Comment by pbrisbin** [comment]
OK good. Then setting those env vars may fix @stefanpenner 's issue.

**Comment by stefanpenner** [comment]
> OK good. Then setting those env vars may fix @stefanpenner 's issue.

Can confirm this works.

It seems like maybe providing a small wrapper that provides good errors might aid users? Otherwise, maybe the readme just need to contain this TL;DR for us OSX users.

**Comment by kevinSuttle** [comment]
It's mentioned in [the README](https://github.com/codeclimate/codeclimate#prerequisites), but agree it should be surfaced or mitigated as in https://github.com/codeclimate/codeclimate/issues/2.

**Comment by pbrisbin** [comment]
With #7 we attempt to catch this on install. Sorry it that wasn't present for you. Glad it's working now.

**Comment by kevinSuttle** [comment]
:+1: thanks!
