### ISSUE TITLE
.codeclimate.yml not found when trying to run validate-config

### ISSUE THREAD

**Issue by scottspeidel** [codeclimate/codeclimate#101]
I created a codeclimate.yml file in my project's root directory and attempted to analyze it with the validate-config command locally. 

From my project's root directory I ran the following commands after the file was already present:

$ docker run codeclimate/codeclimate validate-config
No '.codeclimate.yml' file found. Run 'codeclimate init' to generate a config file.

$ ls -la .codeclimate.yml 
-rw-r--r--  1 scottspeidel  staff  838 Aug 25 14:15 .codeclimate.yml

Is there a way to ask code climate what directory it's looking in? 
Or a way to pass the path in on the command line?

Am I missing something here?

**Comment by pbrisbin** [comment]
Unfortunately, `docker run codeclimate/codeclimate validate-config` isn't enough to properly run the CLI.

You can see the required options in the [README](https://github.com/codeclimate/codeclimate#usage) or [wrapper script](https://github.com/codeclimate/codeclimate/blob/master/codeclimate-wrapper#L45) we provide. Specifically, you need to mount the current directory as `/code` within the container being run.

Let me know if if you have additional questions.

**Comment by scottspeidel** [comment]
@pbrisbin, thanks for the information. I apologize for my oversight.

**Comment by pbrisbin** [comment]
No worries at all! I'm glad it was an easy fix. I'm going to close this, but feel free to reopen if you find it's not working for you with the corrected invocation.
