### ISSUE TITLE
Time taken for reviewing the complete coee

### ISSUE THREAD

**Issue by vipuldarkknight** [codeclimate/codeclimate#1024]
Hello,

I wanted to know if codeclimate uses some kind of caching mechanism to save results over various commits during development process, i have gone through the complete documentation and searched through net but couldn't find anything useful regarding this. Also, if there is caching can you point out on a high-level basis how the caching is being done and how the code review result of previous commits are being used for code review result of next commit.

It would be very useful if you could kindly let me know these details

**Comment by filipesperandio** [comment]
Hi @vipuldarkknight ,

Comparison around different commits and most useful when targeting PRs is what codeclimate.com has to offer on top of the CLI.
The CLI is not meant to aggregate analysis, this has to be done outside of it.

We offer the service for free for public repositories, so check it out!
