### ISSUE TITLE
Issues while fetching/downloading maven dependencies inside engine docker container

### ISSUE THREAD

**Issue by vipuldarkknight** [codeclimate/codeclimate#1025]
Hello there,

Thanks for such a good project to help us out with the code review. I was trying to use maven dependencies inside codeclimate-checkstyle but on running the command mvn jxr:jxr it is unable to fetch/download anything from central repository. I have gone through the configuration and i think codeclimate sets --net to none for all the engines that it uses. I guess setting this variables prevents docker container from using any network. Can you please elaborate on this once? Is this variable configurable or by any means can we use networks inside the docker images(engine images) which codeclimate fetches. Is it possible for us to have network access. 

I would be really thankful if you could reply asap, its kind of urgent project which we are working on right now.

**Comment by filipesperandio** [comment]
Duplicate from https://github.com/codeclimate/codeclimate-checkstyle/issues/34
