### ISSUE TITLE
Docker image latest release

### ISSUE THREAD

**Issue by vladimirtemnikov** [codeclimate/codeclimate#1033]
Hello, I realized that release pipeline is currently broken, so there are no newer docker images for CLI since 0.85.24 release.
Something wrong with ruby gem releasing step, so pipeline stops and step with releasing new docker image never runs.

**Comment by vladimirtemnikov** [comment]
https://app.circleci.com/pipelines/github/codeclimate/codeclimate/203/workflows/a85684a4-46da-4bcd-a1ed-730f4259425e/jobs/2780

**Comment by BrianHawley** [comment]
Make sure to include #1034 too :)

**Comment by BrianHawley** [comment]
CircleCI still is complaining about the `GEM_HOST_API_KEY` environment variable not being defined.

**Comment by vladimirtemnikov** [comment]
@fede-moya thank you for fixes, but there is new one problem when publishing ruby gem:

`You have enabled multifactor authentication but no OTP code provided. Please fill it and retry.`

It will be just great if at least a new docker image will be built, so may be a publishing ruby gem step can be skipped for a while if it's a big problem now?

**Comment by fede-moya** [comment]
I can't apologize enough for this taking so long. It's finally done now.
