### ISSUE TITLE
Support Docker Machines not named "default"

### ISSUE THREAD

**Issue by squaresurf** [codeclimate/codeclimate#108]
I have updated my Mac to replace boot2docker with Docker Machine. Unfortunately it does not seem to work with the codeclimate wrapper script.

```
$ codeclimate                                                                                                                                                                          Your Docker setup does not support the codeclimate wrapper script:

  > /var/run/docker.sock must exist as a Unix domain socket

We require a local Docker daemon that supports communication via the default
socket path.

Please use `docker run' to run the `codeclimate/codeclimate' image directly.

See https://github.com/codeclimate/codeclimate for more details.
```

I do have the Docker env variables set correctly.

```
$ env | grep DOCKER                                                                                                                                                                  DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_CERT_PATH=/Users/daniel/.docker/machine/machines/docker-dev
DOCKER_MACHINE_NAME=docker-dev
```

**Comment by GordonDiggs** [comment]
@squaresurf what version are you running? You can find this out using `docker run codeclimate/codeclimate version`

**Comment by squaresurf** [comment]
@GordonDiggs I'm running version `0.3.1`.

**Comment by pbrisbin** [comment]
@squaresurf I notice you're not using "default" as the docker machine name, which is what the CLI is expecting in its assertions ([source](https://github.com/codeclimate/codeclimate/blob/master/codeclimate-wrapper#L32)).

Are you able to make it so that there is a docker machine available with the name "default"? If that gets things working, we'll know that's the reason and can start to think about how to handle such a scenario.

**Comment by squaresurf** [comment]
@pbrisbin that worked. I was able to get the codeclimate wrapper script by creating a `default` docker machine.

This is definitely going to become an issue as more people migrate. As you can see [in the official docker docs](https://docs.docker.com/machine/get-started/#get-started-with-docker-machine-and-a-local-vm), their instructions name the machine `dev` which would also break the codeclimate wrapper script.

**Comment by pbrisbin** [comment]
@squaresurf glad that got it working. Do you think it's safe to say using `$DOCKER_MACHINE_NAME` (with a default of, well `"default"`) would be the way to go?

**Comment by squaresurf** [comment]
I'm not sure you need a default if the code is only for `docker-machine` since it appears that `docker-machine env` sets `$DOCKER_MACHINE_NAME`

```
$ docker-machine env default                                                                                                                                                           
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.101:2376"
export DOCKER_CERT_PATH="/Users/daniel/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell: 
# eval "$(docker-machine env default)"
```

```
$ docker-machine env docker-dev                                                                                                                                                        
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/daniel/.docker/machine/machines/docker-dev"
export DOCKER_MACHINE_NAME="docker-dev"
# Run this command to configure your shell: 
# eval "$(docker-machine env docker-dev)"
```

**Comment by pbrisbin** [comment]
Cool, thanks. I'm going to re-title the issue. Hopefully we can action the fix soon. Sorry for the trouble.

**Comment by squaresurf** [comment]
@pbrisbin I went ahead and opened a PR to fix this :smile:

**Comment by squaresurf** [comment]
How long before I can expect a release with this fix?

**Comment by GordonDiggs** [comment]
@squaresurf I just released it!

**Comment by squaresurf** [comment]
Thank you @GordonDiggs!
