### ISSUE TITLE
`codeclimate init` error

### ISSUE THREAD

**Issue by albertpak** [codeclimate/codeclimate#116]
when i run `codeclimate init` while I'm in the directory of a project, i get the following error:

```sh
error: (Errno::ENOENT) No such file or directory @ dir_chdir - /code
```

Anyone know what could cause this?

**Comment by pbrisbin** [comment]
Hi @albertpak, it's possible you have restrictive permissions on the current directory which can lead to issues as the CLI tries to read/write/chdir there.

Can you paste the output of the following commands right before you run `init`?

```
pwd
stat .
stat ..
```

Thanks.

**Comment by albertpak** [comment]
Ran: `pwd`
Output: ```/Users/albertpak/Sites/site1```

---

Ran: `stat .`
Output: ```16777220 4627266 drwxr-xr-x 30 albertpak staff 0 1020 "Sep 17 18:27:27 2015" "Sep 17 17:44:16 2015" "Sep 17 17:44:16 2015" "May  2 00:59:10 2015" 4096 0 0 .```

---

Ran: `stat ..`
Output: ```16777220 932628 drwxr-xr-x 20 albertpak staff 0 680 "Sep 18 09:38:35 2015" "Aug 14 15:52:57 2015" "Aug 14 15:52:57 2015" "Oct 31 14:06:13 2014" 4096 0 0 ..```

**Comment by pbrisbin** [comment]
It looks like you're only allowing the execute bit to the all group which is unusual and I think explains why the CLI is unable to change to the directory (note: `/code` within the cli/engines is mapped to the current working directory on the host system).

Is it intentional? If not, you could perform `chmod 755 .` (this may need `sudo`) to set the current directory to more conventional permissions.

**Comment by albertpak** [comment]
I tried `chmod 755 .` and then ran `codeclimate init` and still got the same error

**Comment by pbrisbin** [comment]
And how about with `chmod 755 ..`?

**Comment by albertpak** [comment]
ran it and then ran it with `sudo` permissions

outputs of `stat .` and `stat ..`

--

```
16777220 141713816 drwxrwxrwx 25 albertpak staff 0 850 "Sep 18 11:19:20 2015" "Sep 18 10:39:54 2015" "Sep 18 11:18:58 2015" "Jul 20 23:12:04 2015" 4096 0 0 .

16777220 6156819 drwxr-xr-x 8 albertpak staff 0 272 "Sep 18 11:19:27 2015" "Sep 15 14:58:33 2015" "Sep 15 14:58:33 2015" "May  5 00:25:18 2015" 4096 0 0 ..
```

**Comment by pbrisbin** [comment]
Hmm, actually I misread your `stat` output earlier. Both directories were already `755`, I apologize. It looks like now you've loosened the restrictions on `.` to `777` -- which I would probably try to correct if I were you -- but that wouldn't cause our problem with `init`.

Is there any more to the error message than just that line? A backtrace after, or "Running engine..." before?

**Comment by albertpak** [comment]
nope, it no other messages or anything before or after. just `error: (Errno::ENOENT) No such file or directory @ dir_chdir - /code`

**Comment by albertpak** [comment]
so i finally got it to work, i was running jsut `docker run codeclimate/codeclimate`, but then i changed it to `docker run --interactive --tty --rm --env CODE_PATH="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate` and it worked like it should

sorry for the confusion

**Comment by pbrisbin** [comment]
Ah, that makes sense. A vanilla `docker run` is not expected to work. Sorry for the trouble, glad you got it sorted out.

**Comment by albertpak** [comment]
:) thank you for quick responses

**Comment by ambles** [comment]
`docker run --interactive --tty --rm --env CODE_PATH="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate init` works perfectly fine with me. After the `.codeclimate.yml` is generated, `docker run --interactive --tty --rm --env CODE_PATH="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze` starts the analysis. Good Luck!
