### ISSUE TITLE
CodeClimate CLI Output

### ISSUE THREAD

**Issue by albertpak** [codeclimate/codeclimate#119]
Is there a way to output Codeclimate CLI's console output into a file, like something that `brakeman` gem does for Rails

Brakeman has a command `brakeman -o output.html` - was wondering if Codeclimate CLI had something similar coming?

**Comment by GordonDiggs** [comment]
@albertpak It should support standard UNIX redirection. For example:

```
~ 🐖  codeclimate version > version
~ 🐖  cat version 
0.3.2
```

**Comment by albertpak** [comment]
??? that's not what i was talking about..i was asking about outputting (saving) `codeclimate analyze` output into a file instead of just into console
