### ISSUE TITLE
Help for subcommands

### ISSUE THREAD

**Issue by kevinburkeshyp** [codeclimate/codeclimate#12]
I was trying to figure out whether `codeclimate analyze` takes arguments.. I tried

- `codeclimate -h analyze`
- `codeclimate analyze -h`
- `codeclimate analyze --help`

None of these gave me useful information about the `analyze` command. 

(In particular, the project I'm running it on is large, and eslint keeps timing out, so I'd like to run codeclimate on a few sub-files, not the whole thing).

**Comment by GordonDiggs** [comment]
@kevinburkeshyp This is definitely something we want to improve. For now, `codeclimate help` will display all the commands and what arguments they can take. `analyze` can take an optional `-f` flag that will change the format of the output. Currently the options are 

* `-f text` The default plaintext formatter
* `-f json` A JSON formatter that will output the raw issue data as it comes from the engines.

If you would like to analyze only a subset of files, I would recommend adding to your `exclude_paths`

**Comment by laszlof** [comment]
Further on this. Is there a way to tell it to NOT try to output color? I want to dump the results to a plain text file thats actually readable.

**Comment by pbrisbin** [comment]
@laszlof have you tried outputting to a file? I ask, because I thought the colorizing library we were using was smart enough to not colorize unless connected to a tty. If that's not the case, then yes, we should implement that behavior.

**Comment by laszlof** [comment]
Yup. I just redirected stdout to a file and it dropped all the color codes in there. I didnt notice if there was a -f (file) option. That would probably be the easiest way to implement it. Either that, or a "plaintext" output type.

Another thing I notice that I might as well mention. The json format option produces some odd results. It appears to create individual JSON objects on each line. This isnt what I would expect. I would expect it to produce an array of json objects that could be easily parsed. The entire thing should be a valid JSON object in my opinion.

**Comment by pbrisbin** [comment]
>  I would expect it to produce an array of json objects that could be easily parsed. The entire thing should be a valid JSON object in my opinion.

Yes that makes total sense, and was probably an oversight on our part.

**Comment by ABaldwinHunter** [comment]
Hi @laszlof. Thanks for your feedback! We updated `codeclimate` to output analysis results as a single `JSON` object in version 0.0.19. If you're using homebrew, you can upgrade by running:

```
brew update
brew upgrade codeclimate
```

**Comment by laszlof** [comment]
Thanks! I'll check it out when I get the office tomorrow.

**Comment by ABaldwinHunter** [comment]
@laszlof We updated `codeclimate` to output colorless text when analysis results are piped to a file. Try upgrading with the same commands above. I'm going to close this issue now. :)
