### ISSUE TITLE
boot 2 docker deprecated

### ISSUE THREAD

**Issue by rojotek** [codeclimate/codeclimate#123]
When getting an osx release of boot2docker I saw the following, reporting that boot 2 docker has been deprecated in favour of the docker toolbox: https://www.docker.com/toolbox
https://github.com/boot2docker/osx-installer/releases

![image](https://cloud.githubusercontent.com/assets/261271/10063246/f2a3b7e6-62ae-11e5-8f53-226dece0511b.png)

It would be good to bring your documents in line with this.

**Comment by GordonDiggs** [comment]
@rojotek The CLI is already updated to support Docker Machine. Assuming you have that set up, the rest of the instructions should work! Agreed we should update the docs - will add that to our backlog!

**Comment by GordonDiggs** [comment]
The README is now updated!
