### ISSUE TITLE
How to test engines under development?

### ISSUE THREAD

**Issue by andyw8** [codeclimate/codeclimate#128]
The engine I'm working on can be run against itself with the `analyse --dev` command.

I'd now like to run it against some other codebases. I've tried calling the CLI as follows:

```
docker run \
  --interactive --tty --rm \
  --env CODE_PATH=“/Users/andy/other_code \
  --volume "/Users/andy/other_code":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  codeclimate/codeclimate analyze —dev
```

But  the CodeClimate process just hangs when I try this.

Am I going about this the right way?

**Comment by pbrisbin** [comment]
Hey @andyw8 there are some issues in that code black (smart and missing quotes), is that just paste-fail or is it really what you're trying to run?

Assuming it's just paste-fail, what error are you seeing? I would expect replacing `$PWD` with whatever directory you want to analyze in to work as you're expecting.

**Comment by andyw8** [comment]
Hah, thanks, I've no idea how that smart quote got in there.

Now when I run I'm seeing just `error: (NoMethodError) undefined method `each' for nil:NilClass` but there is no backtrace at all. Is there any way to see that?

**Comment by pbrisbin** [comment]
> Is there any way to see that?

I was going to say unfortunately no, but it looks like someone improved the situation: https://github.com/codeclimate/codeclimate/blob/89d9069c6dc8d8be65b060c0bda8be8403f06559/lib/cc/cli/runner.rb#L14

I think if you pass an additional `-e CODECLIMATE_DEBUG=1`, you'll get a backtrace.
