### ISSUE TITLE
Cannot run `codeclimate analyze`

### ISSUE THREAD

**Issue by stephenprater** [codeclimate/codeclimate#129]
Trying yields:

```
error: (CC::Analyzer::UnreadableFileError) Can't read app/models/benchmarking/benchmarking.rb
```

That's the only thing I get.  Is there a way to see the backtrace or a more verbose error message?  (The file is readable and writable for my user.)

**Comment by pbrisbin** [comment]
Hi @stephenprater does that file happen to be unreadable for the "all" group (permissions `644`)?

The best way to think about it is that codeclimate is an unknown user (for sercurity reasons) so if you want it to analyze a file, it has to be readable by all (not just you).

**Comment by stephenprater** [comment]
That was it!  Thanks for your help.
