### ISSUE TITLE
Throwing error during install

### ISSUE THREAD

**Issue by rjrobinson** [codeclimate/codeclimate#166]
hey I am trying to install the codeclimate via brew. 

`Error while pulling image: Get https://index.docker.io/v1/repositories/codeclimate/codeclimate/images: dial tcp: lookup index.docker.io: no such host` 
thats the error Im getting. 

Im using a fresh install of docker ( docker-machine) 

Thoughts?

**Comment by dblandin** [comment]
Sometimes the docker-machine networking stack gets in a weird state and a restart helps.

```
$ docker-machine restart default
```

Can you give that a try? You may need to change `default` to another name if you've set docker-machine up differently.

**Comment by rjrobinson** [comment]
Thanks. After I restarted I got this error... 

```brew install codeclimate                                                                                                  [8:27:24]
==> Installing codeclimate from codeclimate/homebrew-formulae
==> Downloading https://github.com/codeclimate/codeclimate/archive/v0.9.6.tar.gz
Already downloaded: /Library/Caches/Homebrew/codeclimate-0.9.6.tar.gz
==> env PATH=/usr/local/bin:/usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin PREFIX=/usr/local/Cellar/codeclimate/0.9.6 make install
Last 15 lines from /Users/rrobin008c/Library/Logs/Homebrew/codeclimate/01.env:
2015-10-28 08:27:33 -0400

env
PATH=/usr/local/bin:/usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin
PREFIX=/usr/local/Cellar/codeclimate/0.9.6
make
install

bin/check
An error occurred trying to connect: Get https://192.168.59.103:2376/v1.20/version: dial tcp 192.168.59.103:2376: i/o timeout
Unable to run `docker version', the docker daemon may not be running
Please ensure `boot2docker up` succeeds and you've run `eval $(boot2docker shellinit)` in this shell
make: *** [install] Error 1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/codeclimate/homebrew-formulae/issues```

**Comment by dblandin** [comment]
Ahh, it looks like your shell still has an old IP address for the docker-machine instance. It's trying to connect at `192.168.59.103` and I can see in your docker-machine listing that the IP is actually `192.168.99.100`.

With boot2docker, that IP address was more likely to be static, but with docker-machine, an instance's IP address can change between restarts so you sometimes have to run `eval "$(docker-machine env default)"` after restarting for your shell to pick up the new address.

That line simply sets a few environment variables so your shell can connect successfully. It's a good idea to add it to your `.bash_profile` or `.zshrc` as well.

Here's the command's output without the `eval`:
```
$ docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/[user]/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell:
# eval "$(docker-machine env default)"
```

Can you try running `eval "$(docker-machine env default)"` and trying the install again? You shouldn't have to restart the `dev` instance if you're using `default`.

Sorry for the trouble. Docker can be a little tricky to setup.

**Comment by rjrobinson** [comment]
No worries about the trouble.  I know the issues. I'll try that. Thanks for the help. I'll update you.

**Comment by rjrobinson** [comment]
Thanks for the help. The issue was when I originally installed boot2docker way back, it had me setting env vars.  It was deep... I deleted them, reinstalled all of docker. CC works now. BTW. Love the tool!!!

**Comment by dblandin** [comment]
Awesome! I'm glad we were able to get you setup! Feel free to reach out if you have any feedback. :+1:

**Comment by rjrobinson** [comment]
Thanks again so much
