### ISSUE TITLE
Issue at installation of docker container

### ISSUE THREAD

**Issue by nWidart** [codeclimate/codeclimate#20]
I'm having trouble installing the docker container.

After running `docker pull codeclimate/codeclimate` I'm getting the following error:

```
Post http:///var/run/docker.sock/v1.19/images/create?fromImage=codeclimate%2Fcodeclimate%3Alatest: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
```

When following the steps [here](http://docs.codeclimate.com/article/301-code-climate-cli-troubleshooting#TLS) I get:

```
error in run: Failed to get machine "boot2docker-vm": machine does not exist (Did you run `boot2docker init`?)`
```

Steps I did:

- Install boot2docker
- Run `docker pull codeclimate/codeclimate`

Thanks

**Comment by jonathancadepowers** [comment]
@nWidart Hey. Sorry again for the trouble. Can you try running the following three commands:
```
$ boot2docker init
$ boot2docker up
$ eval "$(boot2docker shellinit)"
```

If that doesn't get things working, can you post the output that you get?

**Comment by nWidart** [comment]
No problem at all, I'm new to docker so I'm sure it's just me not using it properly. :)

Do I have to run the init command in a dedicated folder or something ? Or anywhere is ok ?


Thanks,

**Comment by jonathancadepowers** [comment]
@nWidart I'm pretty sure you can run `boot2docker init` from any location. That's what I'm seeing in my testing.

**Comment by nWidart** [comment]
The steps provided did the trick.

Though it's not clear to me where docker downloaded the iso image, if it's continuously running on background (what I don't want) or where it downloaded the codeclimate docker image.

**Comment by jonathancadepowers** [comment]
@nWidart Glad to hear that did the trick! And great questions:

To see where the `boot2docker.iso` file is stored, run: `boot2docker info`. Then check the value of `"Iso":`.

Using this same command, you can also see if the VM is running or not. Check the `"State":` value.

To stop the VM, pass `boot2docker stop`. Just be sure to start it again the next time you want to run an analysis (by running `boot2docker up`)

Finally, in terms of where the actual Docker images are stored, that's a bit more involved, as boot2docker handles all of this for you. If you do want to see which docker images you have on your machine though, you can run `docker images`.

Thanks for bringing all of these up. I'm going to work on documenting it on our end.

**Comment by nWidart** [comment]
Thank you for the explanation, very helpful. :smile:
