### ISSUE TITLE
DNS Resolution Issues in analyzers

### ISSUE THREAD

**Issue by stphung** [codeclimate/codeclimate#224]
Hello,

I ran into some issues with resolving dns when running an analyzer.  Is this intended behavior? I can produce this behavior by modifying codeclimate-fixme to run a ```wget https://google.com``` which fails due to name resolution problems.

Thanks!
Steven

**Comment by GordonDiggs** [comment]
@stphung Can you describe more of what you're seeing? Do you have some terminal output you could share?

**Comment by stphung** [comment]
Definitely, I have a fork [here](https://github.com/stphung/codeclimate-fixme) which has the changes made in the following test.

1. Build the docker image using ```docker build -t codeclimate/codeclimate-fixme2```
2. Try running the fixme2 engine on a codeclimate enabled project using ```codeclimate analyze --dev -e fixme2```

The output produced is the following:
```
Starting analysis
Running fixme2: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine fixme2 failed with status 4 and stderr
converted 'https://google.com' (ANSI_X3.4-1968) -> 'https://google.com' (UTF-8)
--2015-11-20 19:32:04--  https://google.com/
Resolving google.com (google.com)... failed: Name or service not known.
wget: unable to resolve host address 'google.com'
```

**Comment by GordonDiggs** [comment]
@stphung Ah I see what you're doing now. Engines don't [have access to the network](https://github.com/codeclimate/spec/blob/master/SPEC.md#resource-restrictions), for security reasons. Any network calls you want to make need to be done during the image build process

**Comment by stphung** [comment]
Is this something that can be changed? This disallows doing analysis which
requires building code that in turn may require network access. The
specific use case I am looking at is analysis of Java bytecode.

**Comment by mrb** [comment]
@stphung Hey Steven! Gordon pinged me on this issue because it's my responsibility to make sure that developers building engines have an excellent experience. Let's take this to email - mind shooting me a message at mrb@codeclimate.com ?

**Comment by stphung** [comment]
Sure!
