### ISSUE TITLE
Pylint engine?

### ISSUE THREAD

**Issue by mgracer48** [codeclimate/codeclimate#230]
I would like you guys to add pylint to the analysis, pylint has very useful things like imports not used and arguments not used, etc.

**Comment by mgracer48** [comment]
Make sure u add a config like pep8 has :)

**Comment by dblandin** [comment]
Thanks for the suggestion! We'll keep pylint on our radar moving forward.

In the meantime, if you're interested in building an engine for pylint, you can find our engine spec [here](https://github.com/codeclimate/spec).

Thanks for your interest!

**Comment by mikebryant** [comment]
See #232 - I hadn't actually seen this issue before I started writing the engine. Interesting coincidence!
