### ISSUE TITLE
codeclimate analysis fails but all the engines succeed

### ISSUE THREAD

**Issue by mgracer48** [codeclimate/codeclimate#234]
they all have check next to them
(this is on the site)

**Comment by pbrisbin** [comment]
I @mgracer48 sorry for the trouble, we've seen this happen if something fails outside of the "steps" we capture on the Build page UI.

Would you mind submitting a description of the problem at https://codeclimate.com/help? That way, we'll be able to get more information about what repo this is happening on and try to get to the root issue.

**Comment by dblandin** [comment]
Hey @mgracer48, are you still experiencing this issue?

**Comment by dblandin** [comment]
I'm going to close this issue for now. Feel free to reopen if this is still occurring. Thanks!
