### ISSUE TITLE
Starting the console

### ISSUE THREAD

**Issue by andyw8** [codeclimate/codeclimate#236]
The post at http://blog.codeclimate.com/blog/2015/07/07/build-your-own-codeclimate-engine/ says an engine can be invoked with:

```
Analyzer.new('-e', 'codeclimate/codeclimate-my-engine', '--dev').run
```

but on 0.14.5 this fails with `undefined method 'new' for CC::Analyzer:Module`, I guess because the internal class/module structure has changed?

**Comment by wfleming** [comment]
Hi @andyw8,

Thanks for noticing this. You're correct that the internal implementation changed in a couple ways: the new console invocation would be something like:

```
Analyze.new(['-e', 'my-engine', '--dev']).run
```

Note that you no longer need to provide the entire image name: your docker image should still be `codeclimate/codeclimate-my-engine`, but the CLI invocation just uses `my-engine`. Let me know if you continue to run into trouble with that.

I'll look into updating that blog post as well.

**Comment by mrb** [comment]
@wfleming Thanks! I'll handle the blog update. /c @andyw8
