### ISSUE TITLE
error: (Errno::ENOENT) No such file or directory @ dir_chdir - /code

### ISSUE THREAD

**Issue by lucianosousa** [codeclimate/codeclimate#242]
I just pull the codeclimate docker machine today and receive this error.

```
$ docker run codeclimate/codeclimate init
error: (Errno::ENOENT) No such file or directory @ dir_chdir - /code
```

I'm on OSX El Capitan.

Any thoughts?

**Comment by pbrisbin** [comment]
Hi @lucianosousa the codeclimate image requires a number of options passed to `docker run` to work correctly. It's one of the reasons we ship a wrapper script: https://github.com/codeclimate/codeclimate/blob/master/codeclimate-wrapper#L52

Can you try it again passing similar options?

**Comment by lucianosousa** [comment]
@pbrisbin It's working with all these parameters.

Thanks.
