### ISSUE TITLE
Support for a custom /tmp folder definition.

### ISSUE THREAD

**Issue by envygeeks** [codeclimate/codeclimate#245]
`/tmp/cc` is a terrible name to use by default and ask the host to hold.  It's generic and clashes on our systems where we already have a "/tmp/cc" folder for other stuff.  It would be nice if we could get support for a custom temp folder, and if there already is, have it documented.

**Comment by pbrisbin** [comment]
Hi @envygeeks , sorry about this. I agree it's a problem that we hope to address soon. I'll report back when I have a workaround or actual solution.

**Comment by dblandin** [comment]
Hey @envygeeks,

We recently released [v0.22.1](https://github.com/codeclimate/codeclimate/releases/tag/v0.22.1) of the Code Climate CLI which includes @pbrisbin's updates in #369 regarding mounted code and tmp paths. You can now use a `CODECLIMATE_TMP` environment variable to specify a custom host directory for temporary files during Code Climate analyses.

Now that this enhancement is in place, I'm going to go ahead and close this issue. Thanks!
