### ISSUE TITLE
Exclude does not exclude, it's impossible to exclude.

### ISSUE THREAD

**Issue by envygeeks** [codeclimate/codeclimate#253]
Given the following configuration:
```
engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/SpaceInsideParens:              { enabled: false }
      Rubocop/Style/SpaceInsideBrackets:            { enabled: false }
      Rubocop/Style/BracesAroundHashParameters:     { enabled: false }
      Rubocop/Style/EmptyLinesAroundAccessModifier: { enabled: false }
      Rubocop/Style/EmptyLinesAroundModuleBody:     { enabled: false }
      Rubocop/Lint/FormatParameterMismatch:         { enabled: false }
      Rubocop/Lint/UselessAccessModifier:           { enabled: false }
      Rubocop/Lint/AssignmentInCondition:           { enabled: false }
      Rubocop/Style/SpaceAroundOperators:           { enabled: false }
      Rubocop/Style/AlignParameters:                { enabled: false }
      Rubocop/Style/SignalException:                { enabled: false }
      Rubocop/Style/Documentation:                  { enabled: false }
      Rubocop/Style/DoubleNegation:                 { enabled: false }
      Rubocop/Style/UnneededCapitalW:               { enabled: false }
      Rubocop/Style/IfUnlessModifier:               { enabled: false }
      Rubocop/Style/RescueModifier:                 { enabled: false }
      Rubocop/Style/RegexpLiteral:                  { enabled: false }
      Rubocop/Style/GuardClause:                    { enabled: false }
      Rubocop/Style/FileName:                       { enabled: false }
  fixme:
    enabled: false
exclude_paths:
- .rubocop.yml
- .codeclimate.yml
- .travis.yml
- .gitignore
- .rspec

- Gemfile.lock
- CHANGELOG.md
- readme.md
- README.md
- Readme.md
- ReadMe.md
- COPYING
- LICENSE

- test/**/*
- script/**/*
- vendor/**/*
- spec/**/*
ratings:
  paths:
  - lib/**/*
```

Running:

```
[
    "docker", "run", "--rm", "--env=CODE_PATH=#{Dir.pwd}", \
    "--volume='#{Dir.pwd}:/code'", "--volume=/var/run/docker.sock:/var/run/docker.sock", \
    "--volume=/tmp/cc:/tmp/cc", "-i", "codeclimate/codeclimate", "analyze"
  ]
```

Results in me getting results for anything in vendor, even though it's excluded.  I still get the results. It still calculates on my site for the results, it says my source is their source (which is entirely false.)

```
vendor/bundle/ruby/2.2.0/bundler/gems/jekyll-fdf12efde40c/test/test_utils.rb (5 issues)
```

90% of the problems reported for this source, come directly from vendor/ but vendor, is ignored, is there a workaround?

**Comment by nielsm** [comment]
Getting similar issues locally for other directories

**Comment by wfleming** [comment]
Hi @envygeeks & @nielsm 

Sorry for the delay on this. We have a PR open now (#308) that substantially refactored how we construct the workspace (the paths that analysis operates on). For the reproducible cases we had where exclude paths where not working correctly, the work on that branch has fixed the behavior.

We're hoping to release that fix soon, but until we do we'd encourage anybody having this problem to take a look at that PR & try using a local build of that branch to see if it solves this problem for you.

If you'd like to try out that branch, these would be the steps:

```shell
$ git clone https://github.com/codeclimate/codeclimate.git
$ cd codeclimate
$ git checkout will-pb/serenity-now
$ make
```

The `make` task will build a docker image of the CLI, which will then get used whenever you run `codeclimate` locally.

If you're still seeing results for paths that should have been excluded, please let us know.

**Comment by nielsm** [comment]
@wfleming That seems to have corrected the exclude issues for me.

**Comment by wfleming** [comment]
[v0.18.0](https://github.com/codeclimate/codeclimate/releases/tag/v0.18.0) has been shipped, so our fix for this is now fully released. I'm going to close this issue, but if anybody here continues to experience this on the new release, please feel free to re-open with details.
