### ISSUE TITLE
Engines rely on hard-coded /code paths.

### ISSUE THREAD

**Issue by DavidEBest** [codeclimate/codeclimate#299]
The CodeClimate engines are hard-coded to require the code to live in the `/code` directory. Could that be parameterized?

The reason I ask is that we are attempting to build a Concourse (Concourse.CI) pipeline for continuous compliance scanning. We like the CC approach to Dockerized engines, but Concourse does not allow you to create folders at the root of the file system. Making this change would allow us to easily use the same configuration both inside the CC Platform, and in our own environment.

Thoughts?

**Comment by GordonDiggs** [comment]
Hey @DavidEBest the `/code` location is a requirement in [our spec](https://github.com/codeclimate/spec/blob/master/SPEC.md#input) and is unlikely to change, as it provides a lot of convenience as well as security. It's important to note that `/code` is the directory _inside_ the container - it can be any directory outside the container.

**Comment by dblandin** [comment]
Hey @DavidEBest,

We recently made some enhancements to mounted code and tmp paths in #369 which may be of interest to you.

You can use the `CODECLIMATE_CODE` environment variable (renamed from `CODE_PATH`) to specify a host directory containing application code to be analyzed. This will default to the host machine's current working directory.

You can also use the `CODECLIMATE_TMP` environment variable to specify a host directory that the CLI to use for temporary files during analysis. This will default to `/tmp/cc` on the host machine.

You can use these new environment variables with the recently released version [v0.22.1](https://github.com/codeclimate/codeclimate/releases/tag/v0.22.1) of the Code Climate CLI. Let me know if you have any questions!

**Comment by DavidEBest** [comment]
Thanks for the update! I'll give it a shot.
