### ISSUE TITLE
error: (CC::Analyzer::Engine::EngineTimeout) engine fixme ran for 900000 seconds and was killed

### ISSUE THREAD

**Issue by TheNotary** [codeclimate/codeclimate#315]
I've been updating an opensource codebase to make use of tests, travis-ci, codeclimate, and coverage.  I've installed the codeclimate package, but am hitting this error now which doesn't google what so ever:

```
$ codeclimate analyze

Starting analysis
Running brakeman: Done!
Running bundler-audit: Done!
Running csslint: Done!
Running eslint: Done!
Running fixme: Done!
error: (CC::Analyzer::Engine::EngineTimeout) engine fixme ran for 900000 seconds and was killed
```

Here's the repo from which I'm working:   https://github.com/TheNotary/action-center-platform/tree/891a89fd8c14fc2fe41a4cf8b2f370bb49f433d8

**Comment by wfleming** [comment]
Hi @TheNotary, are you still having this problem? I see you've made quite a few changes to your `.codeclimate.yml` config recently. When I ran `fixme` against your repo locally, it was very fast, so I'm not sure if this was the result of some configuration changes or if something else might be up.

First thing I would suggest is making sure you have the newest versions of the CLI and `fixme`: if you're on OS X a `brew update && brew upgrade codeclimate` should do that.

If after updating you're still seeing this, please let me know.

**Comment by TheNotary** [comment]
Thanks for checking on this @wfleming!  Hmmm... you know I'm not sure what happened, but running `codeclimate analyze` offline seems to be working as one would expect.  I disabled all the ignore statements to try and reproduce some kind of error message but couldn't... many files were deleted locally though which may explain this.  Or gremlins.  

¯\_(ツ)_/¯
