### ISSUE TITLE
Support for shellcheck

### ISSUE THREAD

**Issue by devth** [codeclimate/codeclimate#328]
https://github.com/koalaman/shellcheck

**Comment by sysadmiral** [comment]
They tweeted out about this a while ago: https://twitter.com/codeclimate/status/624265704846585856

I was going to start looking at wrapping shellcheck in an engine soon.

**Comment by GordonDiggs** [comment]
@sysadmiral @devth We have an in-progress engine for shellcheck! https://github.com/filib/codeclimate-shellcheck

If you are interested in getting involved, there are a few open issues on that repo

**Comment by sysadmiral** [comment]
:+1:
