### ISSUE TITLE
Add cppcheck engine

### ISSUE THREAD

**Issue by antiagainst** [codeclimate/codeclimate#351]
Hello Team,

I've created a cppcheck engine [here](https://github.com/antiagainst/codeclimate-cppcheck). Tested and worked on my local machine.

What should be the next step so I can use it in codeclimate.com for my projects?

Thanks!

**Comment by GordonDiggs** [comment]
@antiagainst thank you! We will take a look and let you know about next steps soon!

**Comment by mrb** [comment]
This discussion has been taken offline - the engine is being tested locally!

**Comment by GenaBitu** [comment]
Any progress? It has been several months...

**Comment by antiagainst** [comment]
@GenaBitu: Sorry, I've been busy with some other stuff. Seems dropped the ball. I'll revisit this this weekend.

**Comment by GenaBitu** [comment]
Thank you, no need to apologise :)

**Comment by antiagainst** [comment]
Turned out I didn't really have time last weekend; but still on my TODO list. I hope to find a time for it soon.

**Comment by ramirezd42** [comment]
Anything happening with this? Perhaps the issue could be re-opened?

**Comment by antiagainst** [comment]
Hi @ramirezd42, after @GenaBitu pinged me last time, I [updated the source code](https://github.com/antiagainst/codeclimate-cppcheck/commits/master) for the engine and got up to the point of the ["Copy the Engine QA spreadsheet"](https://docs.codeclimate.com/v1.0/docs/code-climate-engine-lifecycle) step. It's a non-trivial [list of tasks](https://docs.google.com/spreadsheets/d/1hGUh9EGTcRxND_uTJ684vgZV-9O-oRi75RgoEAEp1bE) to tackle down for moving to Beta, especially the "Remediation Points" and "10 Repo tests". For the remediation points, I don't actually have clear ideas of how to assign a number to represent the effort needed for fixing a issue reported by cppcheck. So the effort was paused and I got distracted by other tasks. (Yep, need paycheck for living. :) ) I'm not sure when I'll come back to this issue, but I'll definitely try; you are very welcome to contribute and make it publicly available. Thanks!

**Comment by GenaBitu** [comment]
Hi, wanted to nag again for some time too... Would you consider reopening this issue until it is truly resolved?
Also, did you check off any point on that list? Do you have a specific copy for this engine? I should be able to help with some of them, if that's ok with you, although my experience with Code Climate is limited to say the least...
Feel free to contact me if there is anything I can help with (GitHub or email - genabitu@gmail.com)
Hope this can be solved asap :) Thanks!

**Comment by antiagainst** [comment]
@GenaBitu: Oh, cool! That would be awesome!

Here is the repo: https://github.com/antiagainst/codeclimate-cppcheck

I fixed several other problems today and created [issues](https://github.com/antiagainst/codeclimate-cppcheck/issues) for the things yet to be done. Your help is certainly very welcome! Please just pick the one that you are interested.

As for familiaring yourself with Code Climate tools, here are things helpful:
* [Engine lifecycle](https://docs.codeclimate.com/docs/code-climate-engine-lifecycle)
* [Engine Spec](https://github.com/codeclimate/spec/blob/master/SPEC.md)
* [Engine QA spreedsheet](https://docs.google.com/spreadsheets/d/1hGUh9EGTcRxND_uTJ684vgZV-9O-oRi75RgoEAEp1bE)
* [CLI tool](https://github.com/codeclimate/codeclimate)
