### ISSUE TITLE
Missing .codeclimate.yml file

### ISSUE THREAD

**Issue by afestein** [codeclimate/codeclimate#358]
I have codeclimate CLI installed using homebrew and seems be operational. 

However when navigating to my code directory and running `codeclimate init` for the first time, it reports back `Config file .codeclimate.yml successfully generated.` however there is nothing there. I get the same result if I run the non-wrapper version of that command as set out in the readme.

Interestingly I can add engines using `codeclimate engines:enable rubymotion` and it reports `Engine added to .codeclimate.yml.` yet still there is no file. I can even successfully run analysis and it runs and passes the Rubymotion test without issue.

It seems like it's reading the `.codeclimate.yml` from somewhere else but I'm just not sure what I'm missing here. 

Thanks

**Comment by pbrisbin** [comment]
Hi @afestein this issue is very interesting, I haven't heard of anything like it happening before.

Do you mind running a few commands in your project directory and pasting the complete output here?

```
pwd
ls -la
codeclimate init
codeclimate validate-config
ls -la
cat .codeclimate.yml
```

Also, are you using docker-machine or anything like it? If so, it's possible something funny is going on with the local filesystem vs the VM filesystem, in which case I might have to hand you off to one of my OS X-using colleagues.

Thanks

**Comment by afestein** [comment]
Hey, thanks so much for the quick reply. Yes, I am on OSX using docker-machine as recommended in the readme.

Here are the results:

**pwd**
`/var/www/sites/myproject-motion-ios`

**ls -la**
```
total 232
drwxr-xr-x  28 afestein  wheel    952 27 Feb 09:20 .
drwxrwxrwx   7 root      wheel    238 27 Jan 12:44 ..
-rw-r--r--   1 afestein  wheel   1280 26 Feb 16:40 .env
-rw-r--r--   1 afestein  wheel    710 27 Feb 09:20 .env.development
-rw-r--r--   1 afestein  wheel     51 28 Oct 09:30 .env.test
drwxr-xr-x  16 afestein  wheel    544 27 Feb 09:27 .git
-rw-r--r--   1 afestein  wheel    174 17 Feb 18:08 .gitignore
drwxr-xr-x   9 afestein  wheel    306 25 Feb 18:34 .idea
-rw-r--r--@  1 afestein  wheel     99 26 Feb 17:01 .repl_history
-rw-r--r--   1 afestein  wheel    686 26 Feb 13:00 .rubocop.yml
-rw-r--r--   1 afestein  wheel   1048 26 Feb 13:00 .travis.yml
-rw-r--r--   1 afestein  wheel  11154  4 Nov 13:45 AdHoc_com.myproject.yhi.mobileprovision
-rw-r--r--   1 afestein  wheel  11586  1 Dec 10:20 Adhoc_com.myproject.yhi.staging.mobileprovision
-rw-r--r--   1 afestein  wheel   7490  4 Nov 13:47 AppStore_com.myproject.yhi.mobileprovision
-rw-r--r--   1 afestein  wheel  14094 13 Nov 15:59 Development_com.myproject.yhi.mobileprovision
-rw-r--r--   1 afestein  wheel    605 26 Feb 16:40 Gemfile
-rw-r--r--   1 afestein  wheel   9046 26 Feb 16:40 Gemfile.lock
-rw-r--r--   1 afestein  wheel   2038 10 Dec 17:02 README.md
-rw-r--r--   1 afestein  wheel   2772 26 Feb 16:40 Rakefile
drwxr-xr-x  12 afestein  wheel    408 27 Feb 09:20 app
drwxr-xr-x   8 afestein  wheel    272 27 Feb 09:20 bin
drwxr-xr-x   4 afestein  wheel    136 26 Feb 08:51 build
drwxr-xr-x   3 afestein  wheel    102  3 Dec 15:03 config
drwxr-xr-x  17 afestein  wheel    578 26 Feb 08:59 fastlane
drwxr-xr-x  18 afestein  wheel    612 26 Feb 16:40 resources
drwxr-xr-x   5 afestein  wheel    170  9 Feb 15:57 spec
drwxr-xr-x   5 afestein  wheel    170 26 Feb 16:40 vendor
-rw-r--r--   1 afestein  wheel  14456 25 Feb 18:37 myproject-motion-ios.iml
```

**codeclimate init**
```Generating .codeclimate.yml...
Config file .codeclimate.yml successfully generated.
Edit and then try running 'validate-config' to check configuration.
Generating default configuration for engines...
error: (NoMethodError) private method `select' called for nil:NilClass```

**codeclimate validate-config**
`ERROR: invalid "engines" section: The engines key cannot be empty.`

**ls -la**
Same as above (i.e. no .codeclimate.yml file)

**cat .codeclimate.yml**
`cat: .codeclimate.yml: No such file or directory`

**Comment by pbrisbin** [comment]
What this error always appearing?

```
Generating default configuration for engines... error: (NoMethodError) private method `select' called for nil:NilClass
```

Do you see the `.codeclimate.yml` if you run `sudo ls -la`?

**Comment by jpignata** [comment]
@afestein I just tested locally and was able to reproduce the issue you're seeing on OS X. I believe this is due to docker-machine / VirtualBox only mounting `/Users` within the virtual machine by default. Our image can't see your directory, and we fail inelegantly. Can you copy this directory into your home directory and see if you see the same issue?

**Comment by afestein** [comment]
@pbrisbin Thanks, yes I have seen that error message before, and no I still can't see it using `sudo`. 

@jpignata Yes! That worked:
```Generating .codeclimate.yml...
Config file .codeclimate.yml successfully generated.
Edit and then try running 'validate-config' to check configuration.
Generating default configuration for engines...
Config file .eslintrc successfully generated.
Config file .eslintignore successfully generated.```

Copying the project into my `/Users/afestein` directory did the trick. It all works as expected. 

That's great but I don't want my project folders in with my other junk. How can we improve the project to work around this issue?

**Comment by jpignata** [comment]
@afestein Great. I think your best bet is to mount the /var/www directory from the VirtualBox UI to make sure it is available within your virtual machine. This post outlines the steps that are necessary: http://serverfault.com/questions/674974/how-to-mount-a-virtualbox-shared-folder/674978#674978. Let us know if that doesn't work.

**Comment by afestein** [comment]
OK thanks. I looked into mounting other directories in VirtualBox, but I couldn't get it to work for me easily. Installing guest additions and mucking around with docker config started getting too complicated. 

For my purposes I've decided to just move my project into `~/Code` which is much easier. Here are the full setup scripts I ended up with: 

```
# Set up Code Climate
brew install docker
brew install docker-machine
docker-machine create --driver virtualbox code-climate
brew tap codeclimate/formulae
brew install codeclimate
eval $(docker-machine env code-climate)
```

From there, `codeclimate init` works and here's how I run my tests: 

```
docker-machine start code-climate
eval $(docker-machine env code-climate)
codeclimate analyze
```
