### ISSUE TITLE
Ruby Analysis

### ISSUE THREAD

**Issue by bruno-** [codeclimate/codeclimate#36]
Hi,
thanks for working on code climate and making it a great tool. I was pretty excited when I saw you open sourced a bunch of stuff a couple days ago.

Playing with code climate cli on a ruby project today I realized I can't really get the same output from the cli tool as from your cloud platform. The only ruby engine is rubocop and I can't get for example ruby class grading (A to F), complexity, duplication and security issues etc.. 

Those awesome code climate specific goodies are not open sourced?

Not open sourcing those is reasonable and makes complete sense from the business POV. I'm asking just to make sure I'm not somehow missing a lot of (free) value here.

Thanks and keep up the good work!

**Comment by jonathancadepowers** [comment]
Hey @bruno-

You're right -- the types of Ruby checks that we run on our hosted, [legacy analysis platform](http://docs.codeclimate.com/article/300-analysis-platforms) are currently *different* than what you'll see in our CLI.

Our plan though is to release **more** Code Climate engines to perform the types of Ruby analysis that you mentioned (complexity, duplication, etc.). When those are released, you'll be able to run them within our CLI!

Our team will be working on new engines, plus now that the platform is open/extensible, **anyone** can build their own Code Climate engines as well. So, the scope of engine-based analysis for *all* languages should grow over time.

As far as grades go, those will just be on codeclimate.com.

Great questions! Let us know if we can help with anything else. Thanks!

**Comment by bruno-** [comment]
Hey,
it's good to hear you guys will be open sourcing more engines eventually. That will increase the value of the open sourced CLI tools dramatically.
Be sure to let us know when new engines are out!

Thanks for the fast and friendly response!
