### ISSUE TITLE
faraday_middleware version

### ISSUE THREAD

**Issue by rafamanzo** [codeclimate/codeclimate#360]
Looking at the gemspec blame the version was set on one of the first commits long ago. Is it possible to bump it to `0.10`?

If it implies more work than just bumping it, I can do the work and open a PR.

This is useful in my case since I'm trying to bundle it together with another gem that uses `0.10` and conflicts with codeclimate.

Thanks!

**Comment by wfleming** [comment]
Thanks for this, @rafamanzo. After looking, we actually weren't even using faraday or faraday_middleware anymore: they got removed, but we neglected to remove them from the gemspec at the time.

I've removed them now, and cut a new version, so if you update to `0.21.1` of codeclimate, you shouldn't have this dependency conflict.

**Comment by rafamanzo** [comment]
Nice :) Thank you @wfleming
