### ISSUE TITLE
Symlink not excluding

### ISSUE THREAD

**Issue by bassrock** [codeclimate/codeclimate#37]
I have a project that uses a symlink at app/Resources/node_modules, however when I exclude that path specifically in the codeclimate.yml, eslint does not seem to ignore it. instead I get this error:

```
error: (CC::Analyzer::Engine::EngineFailure) engine eslint failed with status 1 and stderr "fs.js:0\n(function (exports, require, module, __filename, __dirname) { // Copyright Joy\n\nError: ENOENT, no such file or directory '/code/app/Resources/node_modules'\n    at Error (native)\n    at Object.fs.statSync (fs.js:797:18)\n    at /usr/src/app/node_modules/eslint/lib/util/traverse.js:50:27\n    at Array.forEach (native)\n    at traverse (/usr/src/app/node_modules/eslint/lib/util/traverse.js:41:54)\n    at /usr/src/app/node_modules/eslint/lib/util/traverse.js:63:17\n    at Array.forEach (native)\n    at traverse (/usr/src/app/node_modules/eslint/lib/util/traverse.js:41:54)\n    at /usr/src/app/node_modules/eslint/lib/util/traverse.js:63:17\n    at Array.forEach (native)\n"
```

**Comment by pbrisbin** [comment]
@fhwang did we happen to fix this with some recent changes?

**Comment by fhwang** [comment]
While we didn't test that situation exactly, there has been a lot of change regarding both exclusions and symlinks since June 29. I would expect those changes would fix this problem.

@bassrock can you try updating and running it again?

**Comment by bassrock** [comment]
@fhwang One of the latest must have fixed this. To my knowledge it looks like it is working now.

**Comment by pbrisbin** [comment]
Thanks for letting us know @bassrock
