### ISSUE TITLE
Check is marked as executable within gemspec

### ISSUE THREAD

**Issue by sheenobu** [codeclimate/codeclimate#381]
The 'check' command is marked as an executable within the gemspec. However, this is solely for executable ruby files, stated here: http://guides.rubygems.org/specification-reference/#executables

This is an issue when tooling that analyzes gemspecs assumes the executables listed are ruby scripts.

**Comment by GordonDiggs** [comment]
@sheenobu thanks for reporting! I just merged a fix for this and will release it to rubygems shortly.

Out of curiosity, what kinds of tools are you using?

**Comment by sheenobu** [comment]
@GordonDiggs NixOS / Nix Package Manager. At package creation time, the tooling takes a Gemfile (literally gem "codecomplete") and converts it to something nix compatible. 

At package build and installation time, the tooling iterates over spec.executables and wraps them in ruby scripts that sets up the proper environment [\[code\]](https://github.com/NixOS/nixpkgs/blob/b8c489e781a8690c39fb9e967dfafb9ad6a65fa1/pkgs/development/interpreters/ruby/bundler-env/gen-bin-stubs.rb#L23). Additionally, only things in spec.executables get added to PATH (so the codecomplete script doesn't get wrapped or added to PATH, only script and codecomplete-init). I'm packaging this but haven't used it so I don't have context for what gem users need in the PATH.

Guide for packaging ruby packages I am following: https://nixos.org/nixpkgs/manual/#sec-language-ruby

**Comment by sheenobu** [comment]
@GordonDiggs that said, the interested person wanting this package is currently running it via docker so it isn't a blocker on the Nix packaging side. Thought I'd give it a try as packaging is pretty simple when the gemspec matches expectations.
