### ISSUE TITLE
codeclimate init creates .eslintrc file...even if a json one exists

### ISSUE THREAD

**Issue by krainboltgreene** [codeclimate/codeclimate#393]
Currently eslint allows for many types of file names for their rc file, here's a list in order of priority:

http://eslint.org/docs/user-guide/configuring#configuration-file-formats

**Comment by pbrisbin** [comment]
Hi @krainboltgreene thanks for pointing this out, seems like an oversight on our part. I'll let you know when we're able to fix.

**Comment by dblandin** [comment]
This should be fixed as of https://github.com/codeclimate/codeclimate/pull/576. 🎉
