### ISSUE TITLE
Engine failed with status 1 and stderr

### ISSUE THREAD

**Issue by tkqubo** [codeclimate/codeclimate#395]
Hi, 

I'm currently developing `codeclimate-tslint` engine https://github.com/tkqubo/codeclimate-tslint.git, but I am having a trouble when running analysis against `codeclimate-tslint` itself on local machine with docker.

I could run the following lines successfully:

```bash
npm install
docker build --rm -t codeclimate/codeclimate-tslint .
docker run -v $(pwd):/code -v $(pwd)/config.json:/config.json codeclimate/codeclimate-tslint
```

the result of `docker run` seems like exactly what I expect:

```json
{"type":"issue","check_name":"member-access","description":"default access modifier on member/method not allowed","categories":["Style"],"location":{"path":"src/codeclimateConverter.ts","positions":{"begin":{"line":12,"column":3},"end":{"line":20,"column":4}}}}
{"type":"issue","check_name":"object-literal-sort-keys","description":"unsorted key 'check_name'","categories":["Style"],"location":{"path":"src/codeclimateConverter.ts","positions":{"begin":{"line":15,"column":7},"end":{"line":15,"column":17}}}}
{"type":"issue","check_name":"object-literal-sort-keys","description":"unsorted key 'column'","categories":["Style"],"location":{"path":"src/codeclimateConverter.ts","positions":{"begin":{"line":39,"column":7},"end":{"line":39,"column":13}}}}
...
```

But when I run `codeclimate-tslint` via Code Climate CLI like this:

```bash
codeclimate analyze --dev
```

Then it emits status 1 error without further information:

```bash
Starting analysis
Running tslint: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine tslint failed with status 1 and stderr 
```

I'm not sure if I'm doing the right way, but is there anyone familiar with this issue?

**Comment by pbrisbin** [comment]
What is the exit code after your manual `docker run` invocation? Is it in fact `1`?

**Comment by tkqubo** [comment]
I'm so sorry MY CODE was actually calling exit `1` since I misunderstood codeclimate's specification :sob:  Thanks, I will close this issue.

**Comment by pbrisbin** [comment]
No worries! Glad it was an easy fix.
