### ISSUE TITLE
Option to Run Analysis on a Feature Branch Diff

### ISSUE THREAD

**Issue by joncursi** [codeclimate/codeclimate#420]
Say I have `feature-branch-A`, which is a fork from `master`. `master` already has 300 CodeClimate issues; the new code in `feature-branch-A` is introducing 5 more.

Will CodeClimate CLI support the ability to run analysis on _only_ the code changes that `feature-branch-A` has induced (aka isolate the analysis to the 5 new issues that aren't already present in `master`)? Right now it appears that CodeClimate CLI can only report on _all_ issues and is not able to take git diff into account.

Thanks!

**Comment by GordonDiggs** [comment]
Hey @joncursi! Right now, diffing issues is only available on codeclimate.com, not through the CLI. 

We do, however, support analysis of specific files or directories, which I use often in my workflow. Say you're working on file `lib/foo.js`, you can make sure that you aren't introducing issues in that file by running `codeclimate analyze lib/foo.js`. It should cut down on the number of issues (and execution time) you have to look at.

**Comment by leonelgalan** [comment]
Expanding on @GordonDiggs answer, you may also list all the files that change in the feature branch and ran them through `codeclimate analyze` as such:

```sh
git checkout feature-branch-A
codeclimate analyze $(git diff --name-only master)
```

Assuing the feature branch's name is `feature-branch-A` and the base branch is `master`. This will ran the entire file, and not just the changes, through the engines. This won't help much if you already have 300+ issues, but it's a small step forward.

**Comment by leonelgalan** [comment]
More than five years later: (a) forgot about this, (b) thought there must be a solution, and (c) found my own. 

Maybe this should be documented elsewhere, not just as a random comment on a closed issue. Maybe "aliases" or "scripts" (_a la_ NPM's _package.json_) could be added to the codeclimate config, so a user that uses a `main` branch or other way of finding that "diff" could just change that instead. 

My latest experiment is getting `main`'s analysis diffed with `feature-branch`'s own to get closer to codeclimate.com's output.
