### ISSUE TITLE
Docker for Mac support

### ISSUE THREAD

**Issue by sgerrand** [codeclimate/codeclimate#421]
The beta version of Docker for Mac (using `docker` v1.11.x) runs natively on OS X and changes the locations of certain items expected by the `codeclimate-wrapper` script. For example, the Docker socket file at `/var/run/docker.sock` no longer exists on OS X (the container expects this to be passed in).

Will support be added to the wrapper script for Docker for Mac?

**Comment by pbrisbin** [comment]
Thanks for reporting this, it's great that OS X and Windows will soon have native docker.

> Will support be added to the wrapper script for Docker versions >= 1.11.0?

Absolutely. As for _when_, that's a trickier question :)

Our OS X-using developers are very much itching to get off of docker-machine and onto native docker, so as soon as they're able to (it's still invite-only beta right?), I'm sure you'll see patches here that make codeclimate work under that setup. I'd _suspect_ this will happen before 1.11 is released, but we've not done any formal planning for that work yet.

**Comment by sgerrand** [comment]
> sorry, I might've been thinking of Docker for Mac

Your assumption was correct. That's the use case here.

Apart from testing for `docker-machine` etc a lot, the `codeclimate-wrapper` script references `/var/run/docker.sock`. This has moved to `/var/tmp/docker.sock`. By adding a few changes to the conditionals, I've been able to get this script working with Docker for Mac. I'll submit a pull request soon.

**Comment by Mange** [comment]
Just to be a bit pedantic (mostly so people don't get their hype trains running): Docker for {Mac,Windows} is not native docker, it's a tiny VM and an native app that tries to keep it running correctly at all times.
It works almost exactly like native, except for a few problems I hope they'll be ironing out later.

I'm subscribing to this issue as I cannot run `codeclimate` locally right now.

**Comment by sgerrand** [comment]
> Just to be a bit pedantic (mostly so people don't get their hype trains running): Docker for {Mac,Windows} is not native docker, it's a tiny VM and an native app that tries to keep it running correctly at all times.

🙇  You are correct.

![the best kind of correct](http://img.pandawhale.com/149375-You-are-technically-correct-th-31q5.jpeg)

**Comment by sgerrand** [comment]
📝  Updated the title and description of this issue based on @Mange's feedback.

**Comment by sgerrand** [comment]
🎉  Docker for Mac now works with `codeclimate-wrapper` as of v0.25.2.
