### ISSUE TITLE
Gem doesn't load in Ruby 2.0 (uses syntax only available in Ruby 2.1+)

### ISSUE THREAD

**Issue by danielkza** [codeclimate/codeclimate#470]
The gem doesn't load at all in Ruby 2.0 due to usage of mandatory keyword argument, such as in [engines_config_builder.rb](https://github.com/codeclimate/codeclimate/blob/master/lib/cc/analyzer/engines_config_builder.rb#L27).

It would be nice if those usages were replaced by optional keyword arguments, possibly with defaults that raise errors, or that the minimum necessary Ruby version is specified in the gemspec.

**Comment by pbrisbin** [comment]
Hi @danielkza use of this project as a gem isn't really intended. We do it in our own infrastructure but that's an accident of history, and I'd consider it deprecated. This repository is only meant to be used as the Code Climate CLI which runs within a docker container with the appropriate Ruby version -- therefore, we don't worry about wide compatability like that.

I'm curious, what is your use case for loading this as a gem?

**Comment by danielkza** [comment]
We want to integrate the CC collectors into our own code analysis platform called Mezuro ([site](http://mezuro.github.io/), [repo](https://github.com/mezuro). We've been using the gem successfully for some months, and we intended to deploy it to a CentOS 7 setup that only has Ruby 2.0.

If use as a gem isn't intended, it would have been courteous to mention it somewhere, or not make it public on Rubygems.org. :disappointed:

**Comment by pbrisbin** [comment]
I'm sorry you felt mislead and are encountering breakage in your system. If you were to open a PR that added a minimum ruby version to the gemspec, I'd happily merge. Unfortunately, I don't think we're going to worry about if/how this is used as a gem at this time.
