### ISSUE TITLE
Error 400 bad request: malformed host header on first analyze

### ISSUE THREAD

**Issue by slifin** [codeclimate/codeclimate#475]
Running csslint: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine csslint:stable failed with status 1 and stderr 
time="2016-07-27T09:47:24Z" level=fatal msg="Error response from daemon: 400 Bad Request: malformed Host header" 

I called sudo codeclimate analyze after doing an init in the project I'm working on

Running ubuntu 16.04, docker installed with apt-get

**Comment by pbrisbin** [comment]
Hi @slifin we've seen this come up when the docker server has an incompatibility with the client we use in the codeclimate image (the service is Go 1.6 and the client is Go 1.5). Can you run `docker version` to confirm? We've seen this first with Arch Linux users, but Ubuntu may have caught up enough to hit the bug as well now.

**Comment by slifin** [comment]
hi @pbrisbin here is the output: 
`Docker version 1.10.3, build 20f81dd`

**Comment by pbrisbin** [comment]
Sorry, I think that's `docker --version`. Can you post `docker version` (argument, not flag)? That'll include more information.

**Comment by slifin** [comment]
```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/amd64
```

**Comment by pbrisbin** [comment]
OK, that definitely explains it.

Here's some more details if you're interested:

- Original Issue: https://github.com/docker/docker/issues/20865
- Fixes tagged with 1.12 milestone: https://github.com/docker/docker/pull/22000 https://github.com/docker/docker/pull/22888

And here are the options I see to get you working again:

- Rebuild your docker package with go-1.5

  This is what the Arch users have done so far. A little annoying, but at least immediate and in your own hands. There might even be a package available for Ubuntu, I'm not sure.

- We update our client

  I'm not against this, but it'll take us time to fully evaluate and test that impact. There may be users on older dockers that rely on the version we're using (an older client can talk to a newer server, but not the other way around).

- Wait for / upgrade to docker 1.12

  I'm not sure how viable that is for you.

Sorry I don't have better news.

**Comment by paulodiovani** [comment]
> Wait for / upgrade to docker 1.12

Will this be fixed on 1.12?

**Comment by pbrisbin** [comment]
I believe so. I based that on the current milestone for the fixes I linked to above.

**Comment by wfleming** [comment]
Docker 1.12 was released on Aug 18, and has resolved this issue in all the cases we've seen, so I'm going to close this issue for now. If anybody is still affected to this after upgrading to Docker 1.12, please let us know.
