### ISSUE TITLE
Update `activesupport` dependency for Rails 5 compatibility

### ISSUE THREAD

**Issue by dread-uo** [codeclimate/codeclimate#477]
Now, `codeclimate` depends on `activesupport >=4.2.1, ~> 4.2`, while Rails 5 depends on version `5.0.0.1`. This makes it impossible to use codeclimate with Rails 5.

**Comment by pbrisbin** [comment]
Hi @dread-uo, the primary use-case for this project is as a CLI tool via the `codeclimate/codeclimate` docker image. The fact that it's available as a gem is more an accident of history than anything, and is something we plan to move away from soon.

I'm very curious to know your use case for loading this project as a gem, especially in a Rails application.

**Comment by dread-uo** [comment]
We are currently using it at [mezuro.org](https://www.mezuro.org) to collect metrics for PHP projects. To be more accurate, we use it on [kolekti_cc_phpmd](https://github.com/mezuro/kolekti_cc_phpmd), a metric collector we use on [kalibro_processor](https://github.com/mezuro/kalibro_processor), which is the application I am updating to use Rails 5.

**Comment by pbrisbin** [comment]
Thanks for that information. Unfortunately, I'm going to go ahead and close this issue.

We're not against folks like yourself doing this, but we want to be upfront about the fact that we will likely stop releasing this project as a gem soon, and we won't be addressing any Issues like this in the meantime. However, if you were to open a PR correcting these kinds of version bounds problems, we would likely merge it.

I've added some copy to the ISSUE_TEMPLATE to hopefully clarify for future users who encounter this.
