### ISSUE TITLE
Brakeman support ?

### ISSUE THREAD

**Issue by fproulx-pbox** [codeclimate/codeclimate#48]
It does not seem that Brakeman Ruby security is supported now ?

**Comment by pbrisbin** [comment]
Hi @fproulx-pbox -- no, we have not implemented a Brakeman engine yet. That does mean that the new engines-based analysis does not have this feature.

However, our original, non-engines analysis is still fully supported. If you rely on Brakeman, you can keep it by not turning on engines until we've reached feature parity in this way.

We're working hard to port all existing analyses (Brakeman, duplication, python, etc) to the new engines-based platform -- unfortunately, I don't have any concrete timelines to provide just yet.
