### ISSUE TITLE
How can I run a local engine ?

### ISSUE THREAD

**Issue by chollier** [codeclimate/codeclimate#486]
I'm having some issues running an engine in dev, I forked codeclimate-eslint:pb-eslint2 and am trying to run my own version.

Here is what I do :

`docker images | grep codeclimate` output :
<details>
```
 loic@Loics-MacBook-Pro-32  ~/approvals   feature/relay-photo-panel ●  docker images |grep codeclimate
codeclimate/codeclimate-eslint                                                 quri                     0a1a5155ff6b        23 minutes ago      287.6 MB
codeclimate/codeclimate-eslint                                                 eslint-2                 0d7535e245ec        10 days ago         285.9 MB
codeclimate/codeclimate-eslint                                                 latest                   d89d85122804        2 weeks ago         111.1 MB
codeclimate/codeclimate                                                        latest                   e2d0aa19db54        2 weeks ago         96.29 MB
```
</details>

```
 loic@Loics-MacBook-Pro-32  ~/approvals   feature/relay-photo-panel ●  docker run \
  --interactive --tty --rm \
  --env CODECLIMATE_CODE="$PWD" \
  --volume "$PWD":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  -e CODECLIMATE_DEBUG=1 codeclimate/codeclimate analyze --dev -e codeclimate/codeclimate-eslint:quri
```
output: 
<details>
```
Starting analysis
error: (CC::Analyzer::Container::ImageRequired) Unable to find an image for codeclimate/codeclimate-eslint:quri. Available channels: ["stable"].
[DEBUG] backtrace: /usr/src/app/lib/cc/analyzer/engine.rb:59:in `rescue in run'
        /usr/src/app/lib/cc/analyzer/engine.rb:62:in `run'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:60:in `block in run_engine'
        /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:74:in `with_spinner'
        /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:55:in `block in engine_running'
        /usr/src/app/lib/cc/analyzer/formatters/formatter.rb:18:in `engine_running'
        /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:54:in `engine_running'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:59:in `run_engine'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `block in run'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `each'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `run'
        /usr/src/app/lib/cc/cli/analyze.rb:20:in `block in run'
        /usr/src/app/lib/cc/cli/analyze.rb:18:in `chdir'
        /usr/src/app/lib/cc/cli/analyze.rb:18:in `run'
        /usr/src/app/lib/cc/cli/command.rb:24:in `execute'
        /usr/src/app/lib/cc/cli/runner.rb:22:in `run'
        /usr/src/app/lib/cc/cli/runner.rb:8:in `run'
        /usr/src/app/bin/codeclimate:6:in `<main>'
```
</details>

I tried a few things to specify the engine : `eslint:quri` / `codeclimate-eslint:quri` etc but can find the right way

meta:
<details>
```
$ uname -a 
Darwin Loics-MacBook-Pro-32.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
$ docker version 
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true
```
</details>

**Comment by chollier** [comment]
I was actually able to run it by doing 
`docker build . -t codeclimate/codeclimate-eslint`

which overrode the "stable" channel

**Comment by ABaldwinHunter** [comment]
Hi @chollier! Cool. You can run the engine with `docker run` and pass it all of the env vars as you started doing originally.

Or, if you have `codeclimate` CLI installed, you can build your engine and run it by including it in a .codeclimate.yml file or passing the name as an arg to 

```
codeclimate analyze -e my-cool-engine --dev
```

Note the `--dev` flag which allows you to run unofficial engines as you develop them.

You can build the engine from its directory:

`docker build -t codeclimate/codeclimate-my-cool-engine .`

```
$ docker images | grep my-cool-engine

-> codeclimate/codeclimate-my-cool-engine              latest        0d7535e245ec        10 days ago         285.9 MB
```

**Comment by chollier** [comment]
I did build my own engine, if you look at my first output you'll see 

```
codeclimate/codeclimate-eslint                                                 quri
```
I ran `docker build . -t codeclimate/codeclimate-eslint:quri`.
Note that I was also already using `--dev`.

Hmm, so I guess I can't be using `eslint` because it's available channels are built in the codeship image ?

We've been customers of codeclimate for a while and use it with ruby but I've never been able to use it with our front-end javascript projects, mainly because we are using cutting edge tech / versions (eg: first because eslint wasn't supported: corrected, but now we use eslint 3 with our own custom config)
I decided to give it another shot and realized I could be using a custom engine, we use our own `eslint-config-quri` which is a fork of `eslint-config-airbnb`.

What would be the best path to be able to use eslint3 and our own `eslint-config-quri` + other packages in codeship.com ? Would you guys accept a PR to codeclimate/codeclimate-eslint:pb-eslint2 to : 
- add our `eslint-config-quri` ?
- support eslint3 ?

**Comment by ABaldwinHunter** [comment]
@chollier ah great. sorry I missed some of your original output!

To use a custom engine outside of codeclimate.com, you could build a modified image and run with `--dev` as you described.

For general eslint-3 support: we currently have an issue open on the codeclimate-eslint repo for supporting an [eslint-3 channel](https://github.com/codeclimate/codeclimate-eslint/issues/125). 

I'm going to direct you over there and close the issue here. Please feel free to reopen if something else comes up.

Apologies for the delay on the eslint-3 channel -we're eager to add support and plan to add a new branch supporting eslint-3 as soon as possible. If you have time and would like to, please feel free to open a pull against codeclimate-eslint master.

For your `eslint-config-quri` plugin, we vendor in particular eslint plugins but for security reasons don't automatically load all of your npm modules. I'd have to take a closer look to confirm but at the moment we probably wouldn't support that.
