### ISSUE TITLE
Support for Access Lint

### ISSUE THREAD

**Issue by bhubbard** [codeclimate/codeclimate#487]
https://github.com/accesslint

**Comment by wfleming** [comment]
Code Climate engines run [without network access for security reasons](https://github.com/codeclimate/codeclimate/issues/487), and in general our [spec schema](https://github.com/codeclimate/spec) is organized around analyzing & reporting issues on *source code*, not things derived from source code like web pages. So unfortunately, AccessLint is a poor fit for Code Climate. Never say never, I'm just leaving this as a small note on some current hurdles in the way of supporting this tool.
