### ISSUE TITLE
HTML formatter lacks RedCarpet option ":no_intra_emphasis"

### ISSUE THREAD

**Issue by Jacob87** [codeclimate/codeclimate#499]
Command: `codeclimate analyze -f html`

When running the analyzer with HTML output, sometimes method names get messed up by the markdown formatter. Consider the standard PHP function `file_get_contents`. When using the markdown formatter on that method name, the output in the issue description field will be `file<em>get</em>contents`. Method names should never be formatted.

According to the RedCarpet documentation, it should be possible to utilize the option "no_intra_emphasis" to specifically avoid the `<em></em>` markup inside words. I think this could be fixed in lib/cc/analyzer/formatters/html_formatter.rb:63 by changing the line to:
```ruby
Redcarpet::Markdown.new(html, autolink: true, fenced_code_blocks: true, tables: true, no_intra_emphasis: true).render(body)
```

**Comment by maxjacobson** [comment]
@Jacob87 Good catch. Do you want to make a PR with that change?

**Comment by Jacob87** [comment]
It seems the pull request #509 has fixed the apparent issue. But other markdown formatting might be a problem for certain names and descriptions. I was wondering if perhaps the method variables found in the code could be wrapped like \`file_get_contents()\` in the html template, because they are already kind of "pre-formatted". What do you think?

**Comment by maxjacobson** [comment]
That sounds like a good idea @Jacob87. The place to make those changes is in the individual engines. We expect them to emit markdown-formatted messages, and if they use backticks around their variable references, we'll render those as code samples. It seems like, for example, that codeclimate-rubocop already does this:

<img width="747" alt="screen shot 2016-10-19 at 11 27 45 am" src="https://cloud.githubusercontent.com/assets/1421211/19532094/18eca4b6-95ef-11e6-803c-f6d15973d393.png">

I'll close this issue, but feel free to open new ones on the repos for the engines you're using which could emit their messages in a more useful way.
