### ISSUE TITLE
Ask user to auto-init if yml file isn't present

### ISSUE THREAD

**Issue by kevinSuttle** [codeclimate/codeclimate#5]
``` bash
❯ codeclimate engines:enable eslint                                                                     12:57:39 PM
No '.codeclimate.yml' file found. Run 'codeclimate init' to generate a config file.

/Users/kevinsuttle/Code/bluemix-beta (master | ✓)
❯ codeclimate init                                                                                      12:57:43 PM
Config file .codeclimate.yml successfully generated.
Edit and then try running 'validate-config' to check configuration.
```

Similarly to https://github.com/codeclimate/codeclimate/issues/2, if the yml file isn't there, give the user the option to generate one interactively, on their behalf. 

Same goes for "`validate config`". Seems like something the user shouldn't have to do.

**Comment by wfleming** [comment]
We no longer require a `.codeclimate.yml` to be present at all to run `codeclimate analyze`, so this doesn't seem needed anymore. https://github.com/codeclimate/codeclimate/releases/tag/v0.70.0
