### ISSUE TITLE
.codeclimate.yml on Windows

### ISSUE THREAD

**Issue by reedstonefood** [codeclimate/codeclimate#537]
I cannot figure out how to get my own version of the .codeclimate.yml file onto windows.

The website gives me a file that I am to run using "patch" - ie it is assuming a *nix setup. I don't know how to get from this file to what I need.

I have tried manually creating a file according to the examples on the website, but when I commit to GitHub and refresh codeclimate on it, it fails.

Please excuse my noobishness, I know very little about .yml...

**Comment by GordonDiggs** [comment]
@reedstonefood Sorry for the confusion! There are a few implementations of `patch` that you can use.

- One from [GnuWin32](http://gnuwin32.sourceforge.net/packages/patch.htm)
- I've also read that Git on windows ships with one, but am not super familiar with that.

**Comment by reedstonefood** [comment]
In installed that, but it does nothing.

Could you offer some manual help... as setting up the config file(s) would appear to be a one-time thing. I tried copy & pasting what I thought was the right bit from the config file, minus the first column, but to no avail. Perhaps you could have a look at what I have done & why it is wrong?

https://github.com/reedstonefood/machi_koro/blob/master/.codeclimate.yml

**Comment by GordonDiggs** [comment]
@reedstonefood looks like you had a combination of array format and hash format in the duplication languages. I've opened a PR to fix that for you!

**Comment by reedstonefood** [comment]
Ha, nice to know I wasn't missing something obvious. Thanks very much for your help!

**Comment by GordonDiggs** [comment]
No problem! Going to close this issue now
