### ISSUE TITLE
eslint config path not getting passed to codeclimate-eslint

### ISSUE THREAD

**Issue by kjg** [codeclimate/codeclimate#572]
I have a code_climate.yml file with a 
```yaml
  eslint:
    enabled: true
    channel: eslint-3
    config:
      config: path/to/.eslintrc.json
```

but when I run `codeclimate analyze -e eslint:eslint-3`

I get the error
```
/usr/src/app/node_modules/eslint/lib/config.js:170
            throw noConfigError;
            ^

Error: No ESLint configuration found.
    at getLocalConfig (/usr/src/app/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/usr/src/app/node_modules/eslint/lib/config.js:259:26)
    at Config.getConfig (/usr/src/app/lib/eslint-patch.js:34:46)
    at CLIEngine.getConfigForFile (/usr/src/app/node_modules/eslint/lib/cli-engine.js:776:29)
    at module.exports (/usr/src/app/lib/validate_config.js:9:22)
    at Object.<anonymous> (/usr/src/app/bin/eslint.js:236:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```
as far as I can tell using `CODECLIMATE_DEBUG=1` the `path/to/.eslintrc.json` is never getting sent to codeclimate-eslint

**Comment by pointlessone** [comment]
Hi @kjg,

Could you please post your `.eslintrc.json`?

**Comment by kjg** [comment]
The file at path/to/.eslintrc.json is the following

```json
{
  "parserOptions": {
    "ecmaVersion": 5,
    "sourceType": "module",
    "ecmaFeatures": {
      "impliedStrict": true
    }
  },

  "plugins": [
    "standard"
  ],

  "extends": "eslint:recommended",
  "rules": {
    "standard/object-curly-even-spacing": [2, "either"],
    "standard/array-bracket-even-spacing": [2, "either"],
    "standard/computed-property-even-spacing": [2, "even"],
    "no-unused-vars": ["error", { "argsIgnorePattern": "^_" }]
  },

  "env": {
    "node": true,
    "mocha": true
  }
}
```

**Comment by maxjacobson** [comment]
@kjg We've just shipped the fixes in #182, which I believe will resolve your issue. When you get a chance, will you confirm?

**Comment by kjg** [comment]
It looks like you probably mean https://github.com/codeclimate/codeclimate-eslint/pull/182. I'll give it a shot, thanks!

**Comment by maxjacobson** [comment]
@kjg 😅 yep!

**Comment by kjg** [comment]
codeclimate/codeclimate-eslint#182 does not seem to have fixed this particular issue for me

**Comment by kjg** [comment]
It looks like the eslint code is reading engine config from a json file. Where does the yaml get translated to a json file?

**Comment by kjg** [comment]
This appears to be working fine on codeclimate.com, but not on the docker images for some reason. I still get the noConfigError unless I symlink my config to the top level (when running locally)

**Comment by maxjacobson** [comment]
Will you try running `codeclimate engines:install` to make sure you've pulled the latest version of the docker image?

**Comment by kjg** [comment]
Yeah. I did that multiple times and it did updates and I can log into the
image and see the new code. I think somehow the code climate yaml file
isn't sending the path to the config over to the eslint image

**Comment by kjg** [comment]
@maxjacobson Is there any way I can debug this further and see exactly what path the es-lint image is getting for the path to the config?

**Comment by kjg** [comment]
Ah, I have a little more info now. The analysis seems to work when running `codeclimate analyze`, but fails with the `Error: No ESLint configuration found` when passing the engine as a flag `codeclimate analyze -e eslint:eslint-3`

**Comment by kjg** [comment]
Since eslint-3 is no longer a valid channel, I won't run into this issue personally anymore. but maybe it's worth looking into if `codeclimate analyze -e eslint:eslint-2` with a non top-level eslintrc is going to cause issues.

**Comment by maxjacobson** [comment]
Good point. Thanks for your help getting to the bottom of this
