### ISSUE TITLE
Should analyze exit non-zero if there are issues?

### ISSUE THREAD

**Issue by devth** [codeclimate/codeclimate#583]
That's what I would expect, and it helps in cases like CI where we want to fail builds if there are issues. Appears to exit 0 currently:

```bash
Analysis complete! Found 75 issues.

$ echo $?
0
```

Edit: just found the [spec](https://github.com/codeclimate/spec/blob/master/SPEC.md#output). Makes sense, but maybe an ENV var could be used to optionally specify a different behavior where any errors exit 1 for the CI case.

**Comment by wfleming** [comment]
Hi @devth, we have a related issue filed for this already: #422. We don't know when we'll be able to schedule implementing a fix, but we're interested in help getting it done if you're interested!

I'm going to go ahead and close this as a duplicate, but feel free to discuss further on #422.

Thanks.
