### ISSUE TITLE
Prepare by default

### ISSUE THREAD

**Issue by ABaldwinHunter** [codeclimate/codeclimate#593]
### current behavior

When running `codeclimate analyze` on a repo that requires the `prepare` step execution to retrieve remote configuration files, the prepare step doesn't get executed and the error reported to user is that the config file is missing:

```console
Starting analysis
Running rubocop: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine rubocop:stable failed with status 1 and stderr 
/usr/local/bundle/gems/rubocop-0.46.0/lib/rubocop/config_loader.rb:151:in `read': No such file or directory @ rb_sysopen - /code/rails_rubocop.yml (Errno::ENOENT)
	from /usr/local/bundle/gems/rubocop-0.46.0/lib/rubocop/config_loader.rb:151:in `load_yaml_configuration'
	from /usr/local/bundle/gems/rubocop-0.46.0/lib/rubocop/config_loader.rb:34:in `load_file'
	from /usr/local/bundle/gems/rubocop-0.46.0/lib/rubocop/config_loader.rb:89:in `block in base_configs'
	from /usr/local/bundle/gems/rubocop-0.46.0/lib/rubocop/config_loader.rb:77:in `map'
	from /usr/local/bundle/gems/rubocop-0.46.0/lib/rubocop/config_loader.rb:77:in `base_configs'
	from /usr/local/bundle/gems/rubocop-0.46.0/lib/rubocop/config_loader_resolver.rb:21:in `resolve_inheritance'
	from /usr/local/bundle/gems/rubocop-0.46.0/lib/rubocop/config_loader.rb:39:in `load_file'
	from /usr/local/bundle/gems/rubocop-0.46.0/lib/rubocop/config_loader.rb:105:in `configuration_from_file'
	from /usr/local/bundle/gems/rubocop-0.46.0/lib/rubocop/config_store.rb:44:in `for'
	from /usr/src/app/lib/cc/engine/file_list_resolver.rb:38:in `rubocop_file_to_include?'
	from /usr/src/app/lib/cc/engine/file_list_resolver.rb:16:in `block in expanded_list'
	from /usr/src/app/lib/cc/engine/file_list_resolver.rb:13:in `each'
	from /usr/src/app/lib/cc/engine/file_list_resolver.rb:13:in `flat_map'
	from /usr/src/app/lib/cc/engine/file_list_resolver.rb:13:in `expanded_list'
	from /usr/src/app/lib/cc/engine/rubocop.rb:50:in `files_to_inspect'
	from /usr/src/app/lib/cc/engine/rubocop.rb:30:in `block in run'
	from /usr/src/app/lib/cc/engine/rubocop.rb:29:in `chdir'
	from /usr/src/app/lib/cc/engine/rubocop.rb:29:in `run'
	from /usr/src/app/bin/codeclimate-rubocop:17:in `<main>'
```

This message can be confusing. 

### desired behavior

A couple of ideas for improving experience:
- run the `prepare` step by default as part of `analyze` (preferred)
- make the error message a little smarter and suggest running `codeclimate prepare` to ensure all  files present. 

I think the first one seems simplest.

**Comment by maxjacobson** [comment]
For option 1, I could see an argument for only fetching files that otherwise don't exist - that way we don't slow down every analyze. I know it was an intentional decision to require users to explicitly invoke this command, but maybe that would be an acceptable compromise.

For option 2, maybe the CLI can check for the absence of the fetch-files after analysis fails and encourage running `codeclimate prepare` only if they're missing? I don't think it can tell that the engine failed _specifically because the files were missing_ and it would be annoying to suggest fetching files that have already been fetched.

**Comment by wfleming** [comment]
I don't think option 1 is preferred, partially for the reasons Max gave. I would go further and say that I don't think we should even try and be smart enough to only prepare non-existing files, since this could lead to confusion about whether the CLI would automatically check for whether those remote files have changed (it won't).

Personally, I think the error message approach is plenty, probably by just emitting a warning if any files expected to exist from `prepare` don't exist.

**Comment by wfleming** [comment]
> FWIW, running the prepare step seems pretty quick to me, so I don't see a huge downside. 

One of the very nice advantages of the CLI is that you can use it without network access. And not everybody always has fast internet access, even if they are connected.

> Further, one argument in favor of always running the prepare step when configured is that it's consistent with analysis on codeclimate.com.

I would argue doing it automatically makes it *less* like .com. There's a reason `prepare` is it's own step in the build process, same as `init`, etc. `analyze` is intended to be *just* the engines analysis.

> Alternatively we could pass a --prepare flag to analyze.

In terms of user-facing effort, I don't see a significant difference between typing that and typing `codeclimate prepare && codeclimate analyze`, so I don't see that as an improvement (for one thing it begs the question of do we then also add an `--init` flag? What about an `--engines-install` flag? "Simple" solutions are rarely actually that simple :).).

Adding a flag also doesn't solve the the motivating issue here, which is that if you forget/don't know to run `prepare`, the error message you get doesn't tell you you should. So you'd still need to make the improvement to emit a warning.

**Comment by ABaldwinHunter** [comment]
Emitting a warning WFM. 

> What about an --engines-install flag? "Simple" solutions are rarely actually that simple :).

FWIW we do install engines by default when you run `codeclimate analyze`

**Comment by wfleming** [comment]
> FWIW we do install engines by default when you run codeclimate analyze

I wondered if you would call me out on that :). Only as a side effect of `docker run` though, and importantly that doesn't *update* engines that exist locally, it only pulls image not available locally, which makes the current "unintentional side effect" behavior different from what I presume a `--prepare` or `--engines-install` flag would do (which I would expect to run the relevant commands regardless).

**Comment by ABaldwinHunter** [comment]
This issue seems like a behavior suggestion that we don't want at the moment. I'm going to close for now. 

The one valuable action item mentioned seems like better error messaging, but I'm not sure that it's valuable enough to action work at the moment - and maybe deserves its own issue if so.
