### ISSUE TITLE
CLI prints warnings to stdout when the formatter has been set to json or html

### ISSUE THREAD

**Issue by maxjacobson** [codeclimate/codeclimate#609]
As a user, if I run:

```
codeclimate analyze -f json
```

I expect to be able to treat the output as valid json. Unfortunately, the version checker prints to stdout as well, even when the formatter is json or html.

This can break the Atom integration, which shells out to the CLI and attempts to capture the json output: https://github.com/AtomLinter/linter-codeclimate/issues/57

Ideas:

1. When the formatter is not plain text, don't print the version checker warning
1. Or, when the formatter is not plain text, print the version checker warning to stderr

@GordonDiggs tagging you on this so you can figure out how to assign/prioritize it

**Comment by GordonDiggs** [comment]
@maxjacobson good catch! We should do the first idea (don't print the warning)

**Comment by dblandin** [comment]
Sounds like we should additionally always print this warning to `stderr`. Any reason it's currently emitted on `stdout`?

**Comment by maxjacobson** [comment]
I think the idea is that we want the average user to see the warning, so they'll know to upgrade their CLI. In engines, stderr isn't visible by default, but I'm realizing now that may not be the case for CLI code.

**Comment by dblandin** [comment]
Should this be closed now that #611 has merged or do we still want further action?

**Comment by GordonDiggs** [comment]
I think we're set!
