### ISSUE TITLE
Accept code to analyze from STDIN

### ISSUE THREAD

**Issue by GordonDiggs** [codeclimate/codeclimate#618]
In order to better support future editor integrations, it will be valuable to support code snippets to analyze via STDIN. The invocation would be something like:

```
codeclimate analyze < def foo(a, b)
```

Though likely with multiple lines of text. It is ok if the solution to this is only supported in the wrapper script

**Comment by halfpastfouram** [comment]
How would this work with editors? Would the docker image be running as a container and then the code inserted from outside the container?

**Comment by pointlessone** [comment]
This has been resolved in #645. Please refer to that PR for the details.
