### ISSUE TITLE
Override the code path on CLI container

### ISSUE THREAD

**Issue by vovimayhem** [codeclimate/codeclimate#631]
Hi!

I'm currently forced to store the code to be analyzed inside a docker named volume, along/aside with other directories. My plan was to mount said volume into the CLI container, using the `--volume my_volume:/code` option.

However, unless this volume contains the code to be analyzed **at the root, exclusively** (not feasible on my case), this will not work, as there's no way `CC::Analyzer::MountedPath.code` will use any other path besides `/code` as the code-to-analyze location:

```ruby
# lib/cc/analyzer/mounted_path.rb, line 6:
def self.code
  host_prefix = ENV["CODECLIMATE_CODE"]
  host_prefix ||= ENV["CODE_PATH"] # deprecated

  if ENV["CODECLIMATE_DOCKER"]
    new(host_prefix, "/code")
  else
    host_prefix ||= Dir.pwd
    new(host_prefix, host_prefix)
  end
end
```

I'd suggest to add the ability to override the code location using some sort of env var:

```ruby
def self.code
  host_prefix = ENV["CODECLIMATE_CODE"]
  host_prefix ||= ENV["CODE_PATH"] # deprecated

  if ENV["CODECLIMATE_DOCKER"]
     # Uses 'CODECLIMATE_CODE_PATH_ON_CONTAINER', defaults to '/code':
    new host_prefix, ENV.fetch('CODECLIMATE_CODE_PATH_ON_CONTAINER', '/code')
  else
    host_prefix ||= Dir.pwd
    new(host_prefix, host_prefix)
  end
end
```
 
How about that name, '`CODECLIMATE_CODE_PATH_ON_CONTAINER`'? I feel it is too long... Any suggestions? Do you take PR's?

**Comment by vovimayhem** [comment]
I'm also noticing that `CC::Analyzer::MountedPath#initialize` accepts a third parameter `path`, however it is not being used by the `CC::Analyzer::MountedPath.code` factory method...

**Comment by vovimayhem** [comment]
*I've renamed the var to `CODECLIMATE_CODE_PATH`*
I've realized that for this to work, every engine should understand ENV["CODECLIMATE_CODE_PATH"]

Is that feasible?

**Comment by pbrisbin** [comment]
Hi @vovimayhem this is a really interesting use-case. Let me test some things out and report back with suggestions for how we might accomodate.

**Comment by vovimayhem** [comment]
I was avoiding having to do something to checkout a worktree from a git repo into the root of a volume, because I knew I had to spend a couple of days on that... and basically rewrite the whole process...

...which I did: [Go Fetch! - Why?](https://github.com/IcaliaLabs/go-fetch#why)

However, I'm still interested on whatever can be done on codeclimate's side :)

**Comment by pbrisbin** [comment]
I'm glad you were able to work around this @vovimayhem. Most likely we wouldn't have been able to make changes on our end in a timely matter.

We have broader plans for supporting projects where the code to analyze exists in a sub-directory of the checkout. This is mostly intended to support folks using a monorepo approach to organizing their projects, which is becoming more common these days, but such a feature would've also solved your use case.

I'm not sure what the feature will eventually look like, or when it might land, but the fact that it was on the horizon is motivation to avoid making orthogonal, more acute changes in this area at this time.

I'm going to go ahead and close this, but if you feel there's more here to discuss, and it's worth keeping open during that discussion, feel free to re-open.
