### ISSUE TITLE
Provide better documentation

### ISSUE THREAD

**Issue by jhabdas** [codeclimate/codeclimate#660]
After generating my `.codeclimate.yml` file using the CLI I, of course, need to know what things are doing so I understand my own codebase.

After reviewing the this repo's `README` file I cannot find information nor links to help make sense of the config generated. And the repo itself simply points at a marketing page on the CodeClimate website: https://codeclimate.com/.

Please provide a better DX (Developer Experience) for your users and work on your documentation and FUX (First-time User Experience).

**Comment by jhabdas** [comment]
For improved DX, please consider creating a separate dev docs site under your TLD and providing more in-depth and detailed information, and consider open sourcing the docs for the benefit of public discussion.

**Comment by GordonDiggs** [comment]
Hi @jhabdas! We currently have documentation at https://docs.codeclimate.com, including a large page about configuration. Additionally, you can use `codeclimate help` to understand what the CLI commands do.

We are constantly improving our docs and hope to make contributing them easier in the future.

I'm going to close this now as there aren't changes to be made to the CLI to improve this. If you have suggestions on how to improve our README, I would be happy to discuss them on a pull request!
