### ISSUE TITLE
Add include_paths option

### ISSUE THREAD

**Issue by jhabdas** [codeclimate/codeclimate#662]
https://docs.codeclimate.com/docs/excluding-files-and-folders shows us how to _exclude_ files from code climate. But what if we want control to _include_ them as well?

At current it's only possible to exclude files using the `exclude_paths` option in `.codeclimate.yml`. This can be somewhat restrictive, event with globbing in place. Thoughts on adding an `include_paths` option with globbing and perhaps some kind of support for providing multiple file extensions of multiple types using bracket expansion, e.g.

```
include_paths:
  - "src/**{*.php,sample.inc}"
  - "tests/**.php"
exclude_paths:
  - "src/assets/*"
```

The expansion stuff comes from EditorConfig and how it's configured. If globbing doesn't currently support something like that it seems like it should IMHO. And the `include_paths` seems like it should just be there if it isn't already.

**Comment by pointlessone** [comment]
Try negated excludes:
```yaml
exclude_paths:
  - "src/assets/*"
  - "!src/**{*.php,sample.inc}"
  - "!tests/**.php"
```

That is globs with `!` prefix.

**Comment by pointlessone** [comment]
I wander why you need to explicitly include files. Aren't they all included by default?

**Comment by jhabdas** [comment]
> Aren't they all included by default?

Yes, they are, including things like images which to me made no sense like config, dotfiles and images. As opposed to trying to blacklist everything I was looking for a way to simply whitelist the things I want scanned. The negation should do the trick. Hopefully rules can conflict with each other and later rules will take precedence (e.g. negate everything, then include the right things).

I find it's also a little funky to have `ratings` and `exclude_paths` in separate places, but I'm just getting into this and am not aware of previous design decisions and why they were made.

Thanks for you help @pointlessone!

**Comment by jhabdas** [comment]
Okay that worked. Here's what I did for ratings to perform the whitelisting:

```yml
ratings:
  paths:
    - "!src/**/*"
    - "src/**.php"
```

Not the most intelligible thing in the world but at least it works.

**Comment by jhabdas** [comment]
This appeared to do what I wanted. Not really intuitive but it seems to be working:

```yml
ratings:
  paths:
    - "src/**.php"
    - "tests/**.spec.php"
exclude_paths:
  - "src/**/*"
  - "!src/**.php"
  - node_modules/
  - "**/vendor/**/*"
```
