### ISSUE TITLE
Codeclimate CLI tool missing in gemspect executables

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [codeclimate/codeclimate#712]
Hello, simple problem: `codeclimate` (the executable) is not included in the gemspec anymore.
There is only a `codeclimate-init` executable, however the website doesn't show any documentation regarding it.

Is this an oversight or you are migrating to something different and I'm supposed to use only `codeclimate-init`?

Thanks

**Comment by ale7714** [comment]
Hi @Fire-Dragon-DoL! We changed the executable name ([PR](https://github.com/codeclimate/codeclimate/pull/140)) to avoid collisions with the binstub distributed on our Docker image. 
Currently we recommend using the CLI following our docker based instructions. You can read about it [here](https://github.com/codeclimate/codeclimate#installation). Let me know if you have any other questions.

**Comment by Fire-Dragon-DoL** [comment]
Oh ok thanks @ale7714 I got really sidetracked because on the website v1.0 and v2.0 the documentation says very different things on how to setup various things. Thanks, I'll make sure to use the docker version!

**Comment by ale7714** [comment]
@Fire-Dragon-DoL sorry for the confusion, feel free to contact us through the [support form]( https://codeclimate.com/help) if you need help setting up Code Climate .
