### ISSUE TITLE
codeclimate/nsp support for package-lock.json 

### ISSUE THREAD

**Issue by amitrai99** [codeclimate/codeclimate#744]
## Guidelines

We are trying to integrate node security platform with our current Front End project.
However, it seems [code climate nsp](https://github.com/codeclimate/nsp), [supports only npm-shrinkwrap.json](https://github.com/nodesecurity/nsp#code-climate-node-security-engine) currently.

Since the original [nsp project](https://github.com/nodesecurity/nsp) on which codeclimate nsp is built on now [supports](https://github.com/nodesecurity/nsp/commit/1d0b7b5ca145d30db062aa246f0bc2e3e3aa77f3) `package-lock.json` I don't see why code climate document still says that it cannot support it.

Can you please upgrade to the latest version of [nsp](https://github.com/nodesecurity/nsp) so that this feature is enabled by default. Without this the integration is meaningless for us.

As an aside there is already some work afoot in the [nsp project](https://github.com/nodesecurity/nsp) to support yarn lock file too. So it would be great if you enable that too once it is complete.

**Comment by dblandin** [comment]
Nice! That's very exciting. I'll queue up an engine update.

**Comment by abbyarmada** [comment]
@dblandin can we make sure we update the doc for NSP to mention this once it's updated? https://docs.codeclimate.com/docs/nodesecurity

Thanks!

**Comment by amitrai99** [comment]
@dblandin thanks for the quick response. Hope to see the update soon.

**Comment by amitrai99** [comment]
@dblandin Any update on this issue?

**Comment by dblandin** [comment]
Hey @amitrai99,

I'm waiting for the updates in the [3.0.0 branch](https://github.com/nodesecurity/nsp/tree/3.0.0) of nodesecurity/nsp to hit master before releasing an engine update.

I also have [a PR][pr] open against that branch with some Dockerfile fixes.

[pr]: https://github.com/nodesecurity/nsp/pull/200

**Comment by amitrai99** [comment]
I wonder if you have information about the nsp 3.0.0 release schedule.

**Comment by dblandin** [comment]
Hey @amitrai99,

I asked and it looks like they're pretty close! https://github.com/nodesecurity/nsp/pull/200#issuecomment-335926978

**Comment by amitrai99** [comment]
@dblandin Since nsp has been upgraded to `v3`, hope to see the engine upgrade very soon.

**Comment by dblandin** [comment]
@amitrai99 We hope to get that out soon! Very exciting!

**Comment by zanona** [comment]
Hey guys, one question it seems the latest update also supports `yarn.lock` correct?

**Comment by amitrai99** [comment]
@zanona for yarn.lock support you will need to use a pre-processor.

See https://github.com/nodesecurity/nsp/pull/187#issuecomment-334624079

**Comment by zanona** [comment]
@amitrai99 That's great, thanks!
@dbergey by any chance are pre-processors already implemented on `.codeclimate.yaml`? — I couldn't find any references to it, I'm afraid. Thanks.

**Comment by amitrai99** [comment]
@dblandin Is there a way to set the build status to warning instead of errors. I want to get all the security warnings but not necessarily force the build to fail due to security errors.

**Comment by msteward** [comment]
@dblandin Looks like the NSP version used by CodeClimate now supports the pre-processors (so that `yarn.lock` can be used but it doesn't look like this can be configured using `.codeclimate.yaml` as mentioned by @zanona above. Is there any timeline for adding a configuration option to enable a pre-processor?
