### ISSUE TITLE
pep8: rule W503 should be ignored by default

### ISSUE THREAD

**Issue by krzysieq** [codeclimate/codeclimate#745]
PEP8 rule W503 "Line break before binary operator" is obsolete and should be ignored by default. However, codeclimate.com analysis still produces warnings related to this rule, even if no setup.cfg file is provided.

It would be nice to have the default codeclimate behaviour match the current PEP8 recommendation.

**Comment by eutopian** [comment]
Closing because I think this has been updated with the pep8 engine. If the rule is still not ignored, please comment and will look into it again.
