### ISSUE TITLE
Front-End Issue Displaying Code Section Content

### ISSUE THREAD

**Issue by alexhernandez** [codeclimate/codeclimate#749]
On Safari Version 11.0 (12604.1.38.1.7)

![code-climate](https://user-images.githubusercontent.com/2424355/31362639-674956fe-ad0e-11e7-8955-88b94f479d39.png)

**Comment by ale7714** [comment]
Hi @alexhernandez, thank you for reporting this. It seems like an oversight on our part. I'll let you know when we release a fix for this.

**Comment by ale7714** [comment]
Closing this issue because we're tracking the bug internally. I will post an update when is done.
