### ISSUE TITLE
New docker image please

### ISSUE THREAD

**Issue by snowblink** [codeclimate/codeclimate#752]
rubocop-0.50 channel has been available for a week and your documentation even says that it is available. In master, this is true, but the latest docker image is from August. Please could you release an updated docker image?

**Comment by maxjacobson** [comment]
Hey @snowblink, looks like we're overdue for a release. Good catch. I'll cut a v0.68.0 now

**Comment by maxjacobson** [comment]
@snowblink All ready, thanks for the nudge: https://github.com/codeclimate/codeclimate/releases/tag/v0.68.0
