### ISSUE TITLE
Cannot find module `babel-eslint`

### ISSUE THREAD

**Issue by stickel** [codeclimate/codeclimate#79]
Updated to `codeclimate v0.2.5` and each time I run `codeclimate analyze` the output shows that it can't find the `babel-eslint` module. I've installed `eslint` and `babel-eslint` globally (`npm install -g eslint babel-eslint`), stopped and restarted `boot2docker` with no change in the output.
```shell
== app/app.js (1 issue) ==
0:0-0:0: Cannot find module 'babel-eslint' [eslint]

== app/components/button/button.js (1 issue) ==
0:0-0:0: Cannot find module 'babel-eslint' [eslint]
```

`.codeclimate.yml`
```yaml
---
engines:
  eslint:
    enabled: true
ratings:
  paths:
  - "**.js"
```
`.eslintrc`
```js
{
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "node": true
  },
  "ecmaFeatures": {
    // ... snip
  },
  "rules": {
    // ... snip
  }
```
Removing `"parser": "babel-eslint"` from `.eslintrc` will output eslint warnings/errors. Is `parser` not a requirement in the eslint config for the codeclimate CLI?

**Comment by GordonDiggs** [comment]
@stickel Unfortunately we don’t support ESLint modules just yet — sorry about that. We do have plans to better support these down the road, there's just more dev work to do on our end before that will be possible. Sorry for the limitation in the meantime though.

**Comment by stickel** [comment]
Alright, thanks for the info/update @GordonDiggs

**Comment by emosbaugh** [comment]
+1

**Comment by knownasilya** [comment]
Is there a date that we could expect this to be supported? Basically makes codeclimate useless for any modern apps.

**Comment by tomchentw** [comment]
I really like the interface provided by codeclimate and hope this could be fixed soon. Thanks a lot :100:

**Comment by cilindrox** [comment]
+1

**Comment by wfleming** [comment]
@cilindrox while we are not yet able to support custom-installed ESLint plugins, we do have several plugins baked into our [eslint engine](https://github.com/codeclimate/codeclimate-eslint), and `babel-eslint` is one of them, so it is supported. You can add `"parser": "babel-eslint"` to your `.eslintrc.*` Our [docs page](https://docs.codeclimate.com/docs/eslint) has more info on which plugins are currently supported.

**Comment by cilindrox** [comment]
@wfleming using standard JS style which we enforce via the [eslint-config-standard plugin][1], so I'm on the same boat as some of the other folks here :/

[1]: https://github.com/feross/eslint-config-standard

**Comment by wfleming** [comment]
@cilindrox Ah, sorry: this issue was filed for the `babel-eslint` plugin so I mistakenly presumed that's what you wanted to use, sorry. Supporting arbitrary plugins is something we'd love to do, but we're not there yet. Stay tuned, though. Sorry it's not possible today.

**Comment by abey-alex** [comment]
+1
