### ISSUE TITLE
Cognitive Complexity engine

### ISSUE THREAD

**Issue by suan** [codeclimate/codeclimate#791]
Hi, I don't seem to be able to run the Cognitive Complexity check locally - is that simply not supported?

**Comment by dblandin** [comment]
Hi @suan,

Looks like we released version `0.7.0` of the CLI on November 20th which includes the new maintainability checks: https://codeclimate.com/changelog/5a0e488824cfa902a300091c

You can update locally using your package manager (homebrew, pacman, etc) or by pulling the most recent docker image: `docker pull codeclimate/codeclimate`.

**Comment by maxjacobson** [comment]
Going to close this, but feel free to let us know if there are any more questions
