### ISSUE TITLE
CodeClimate Test Command appears to be broken

### ISSUE THREAD

**Issue by berfarah** [codeclimate/codeclimate#811]
Hi there! I'm running `codeclimate test` locally and it seems like it's broken.

**What I'm running**
```
brew tap codeclimate/formulae
brew install codeclimate
codeclimate test
```

**Docker Image**
```
codeclimate/codeclimate               latest              bc06bc022f51        3 weeks ago         110MB
```

**Error**
```
error: (NameError) undefined local variable or method `engine_registry' for #<CC::CLI::Test:0x005582b82a37b8>
```

Upon inspection of the [corresponding file](https://github.com/codeclimate/codeclimate/blob/master/lib/cc/cli/test.rb#L243) for this class, it looks like `engine_registry` is indeed not defined anywhere (including the [class it inherits from](https://github.com/codeclimate/codeclimate/blob/master/lib/cc/cli/command.rb)). Looks like there may have been unintended consequences from an [upstream change](https://github.com/codeclimate/codeclimate/commit/ed54c1c88d07cf617730d6952482edde1e20d697#diff-852f0af247380a385edadceea11a9380).

**Comment by wilson** [comment]
Thank you for the report, and for investigating the source of the problem. I'll take a look asap.

**Comment by tedmiston** [comment]
Hi guys - I ran the same command as OP, then also `codeclimate engines:install` and am seeing a similar error.

```
$ CODECLIMATE_DEBUG=1 codeclimate test pep8
error: (NameError) undefined local variable or method `engine_registry' for #<CC::CLI::Test:0x00557db93b6ac8>
D, [2018-03-01T04:27:04.259700 #1] DEBUG -- : backtrace: /usr/src/app/lib/cc/cli/test.rb:243:in `engine_image'
	/usr/src/app/lib/cc/cli/test.rb:227:in `null_container_id'
	/usr/src/app/lib/cc/cli/test.rb:231:in `remove_null_container'
	/usr/src/app/lib/cc/cli/test.rb:94:in `ensure in test_engine'
	/usr/src/app/lib/cc/cli/test.rb:94:in `test_engine'
	/usr/src/app/lib/cc/cli/test.rb:84:in `run'
	/usr/src/app/lib/cc/cli/command.rb:73:in `execute'
	/usr/src/app/lib/cc/cli/runner.rb:25:in `run'
	/usr/src/app/lib/cc/cli/runner.rb:9:in `run'
	/usr/src/app/bin/codeclimate:12:in `<main>'

$ CODECLIMATE_DEBUG=1 codeclimate test markdownlint
error: (NameError) undefined local variable or method `engine_registry' for #<CC::CLI::Test:0x0055db51a44b88>
D, [2018-03-01T04:30:18.319967 #1] DEBUG -- : backtrace: /usr/src/app/lib/cc/cli/test.rb:243:in `engine_image'
	/usr/src/app/lib/cc/cli/test.rb:227:in `null_container_id'
	/usr/src/app/lib/cc/cli/test.rb:231:in `remove_null_container'
	/usr/src/app/lib/cc/cli/test.rb:94:in `ensure in test_engine'
	/usr/src/app/lib/cc/cli/test.rb:94:in `test_engine'
	/usr/src/app/lib/cc/cli/test.rb:84:in `run'
	/usr/src/app/lib/cc/cli/command.rb:73:in `execute'
	/usr/src/app/lib/cc/cli/runner.rb:25:in `run'
	/usr/src/app/lib/cc/cli/runner.rb:9:in `run'
	/usr/src/app/bin/codeclimate:12:in `<main>'
```

Other commands like `$ codeclimate engines:list` seem to be working as expected.  I installed via homebrew today.

On the Docker side, I'm running the latest Docker for Mac edge channel.

```
$ docker --version
Docker version 18.03.0-ce-rc1, build c160c73
```

**Comment by ale7714** [comment]
@berfarah @tedmiston  👋 

Thank you for your detailed issue report. And also, sorry for the delay response. The command `test` is currently a deprecated/undocumented command, that we're not actively supporting anymore. I suspect you may have found an out of date docs page, is that case? If so, can you please share the link with me so we can update it properly. Also, I wanted to ask what are you using this command for? 

Again, thanks!

**Comment by tedmiston** [comment]
@ale7714 Thanks for updating!

I ran `codeclimate --help` which had the test command in the output.

I was trying to figure out exactly what the test command did.  I poked around https://github.com/codeclimate/pep8 but didn't see any particular tests that it would run, so was just curious what test was supposed to do.

```
t-mbp:~ taylor$ codeclimate --help
Usage: codeclimate COMMAND ...

Available commands:
    analyze [-f format] [-e engine[:channel]] [path]    Run analysis with the given arguments
    console                                             Open a ruby console for the CLI. Useful for developing against the CLI.
    engines:install                                     Pull the latest images for enabled engines in your configuration
    engines:list                                        List all available engines
    help [command]                                      Display help information.
    prepare [--allow-internal-ips]                      Run the commands in your prepare step.
    test <engine_name>                                  Test an engine.
    validate-config                                     Validate your .codeclimate.yml or .codeclimate.json.
    version                                             Display the CLI version.
```

**Comment by berfarah** [comment]
@ale7714 Same here - also found it through the `--help` flag

**Comment by ale7714** [comment]
Thanks for reporting this! Good catch. On a recent [PR](https://github.com/codeclimate/codeclimate/pull/817), we removed this command and on the next release it won't be available anymore. Sorry for the confusion!

**Comment by tedmiston** [comment]
Is the idea that this command will be superseded by something or dropped?  I wasn't sure if it turned around to run unit tests on the particular tool being integrated or if CC was writing some custom tests around the engine working, etc.  Or maybe it's just completely unnecessary and we should assume if we can run `analyze` that the engine is working as expected?

**Comment by ale7714** [comment]
@tedmiston it's being dropped. Actually. this was an experimental command that we didn't got around to implement correctly. It's not necessary. Sorry if it caused some confusion.

> we should assume if we can run analyze that the engine is working as expected?

That's correct. We have in-depth details on how to build an engine over here https://docs.codeclimate.com/docs/building-a-code-climate-engine. You can also join our community Slack over [here](https://codeclimate.com/dev_form/).
