### ISSUE TITLE
 CodeClimate Consider React`s Component calls with different parameters as repeated code.

### ISSUE THREAD

**Issue by DanielFaria** [codeclimate/codeclimate#816]
Hi Everyone.

I had a custom component who was called with differents parameters.

Code Climate consider all calls as repeated code: 

Here some part of my code:

`<CheckBox`` id={'souAVitima'} label={'Sou a Vítima'} onClick={e => this.handleChange(e.target.checked,` 'souAVitima')} /> `

`    <CheckBox id={'conhecoAVitima'} label={'Conheço a Vítima'} onClick={e => this.handleChange(e.target.checked, 'conhecoAVitima')} />
`
CodeClimate consider both equal  even with differents parameters. 
I have see some topics about disable code similarity. I don`t like this idea..

Here`s my codeclimate.yml 

`engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc.json
    
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
exclude_patterns:
- "**/testeFuncional/"
- "src/**/*.test.js"`

The Project`s Code is hosted here: 

https://github.com/Enegrecer/enegrecer-web

The pull request with this errors is here:

https://codeclimate.com/github/Enegrecer/enegrecer-web/pull/127

Thank you.

**Comment by wfleming** [comment]
Really sorry this slipped out of my inbox and I forgot about it.

I'm fairly sure this would have been identified as *similar* code, not identical. See our docs for a description of this: https://docs.codeclimate.com/docs/duplication-concept. But, in brief: similar code is code that is structurally the same but may have different identifiers/arguments, etc.

Similar code is of course a slightly more heuristic kind of check, and is more likely to identify things you don't consider a problem. You can configure the similar code check to have a higher threshold (how much code needs to match before it shows an issue), or turn it off entirely: https://docs.codeclimate.com/docs/advanced-configuration#section-default-checks.

**Comment by wfleming** [comment]
Closing this, as I think I've explained the reasons behind this and how to change the behavior if desired. I will still see further comments here if needed.
