### ISSUE TITLE
Fix Documentation at https://docs.codeclimate.com/docs/github to be more precise

### ISSUE THREAD

**Issue by Shantanu-Kotambkar** [codeclimate/codeclimate#822]
The steps at https://docs.codeclimate.com/docs/github, are not directing me to setup the other two code climate checks, that should occur when a pull request is done

**Comment by davehenton** [comment]
Hey @Shantanu-Kotambkar, thanks for the heads up. I've added a step to our section [here](https://docs.codeclimate.com/docs/github#section-show-me-how) to make that a little clearer. I appreciate you looking out!

**Comment by Shantanu-Kotambkar** [comment]
I was able to resolve the issue, I had previously turned the checkboxes off
for test coverage, and diff coverage in the settings. Please add it in the
documentation, as It is not mentioned anywhere in the documentation.
