### ISSUE TITLE
Clean output in json with timeout

### ISSUE THREAD

**Issue by PurpleBabar** [codeclimate/codeclimate#826]
Hi all,

Thanks for the cli, which is great by the way :)

Is there a way to have a valid json file when using the timeout of containers ? 
CONTAINER_TIMEOUT_SECONDS=1800 codeclimate analyze

For now the only way would be to delete the error message at the end ( error: (CC::CLI::Analyze::EngineFailure) engine phpcodesniffer ran for 60 seconds and was killed ) and replace it with "]". Adding a --graceful-timeout to codeclimate cli could be a solution. What do you think of that ? 

Thanks 
Purplebabar

**Comment by PurpleBabar** [comment]
Hi :) 

Thanks for the answer :)

Well, the use case is, i'd like to have a partial result :p. The eroor that occurred is not an error generated by software issue, i'm willingly producing it by setting low timeouts.

The code that i'm analyzing is really big and contains a lot of legacy code. The thing is,having an enormous report would not be practical, and i imagined a way to progress where, i'd have a timeout of 60 seconds, a small report, that i can correct in one week, and week by week i would be able to correct errors, step by step...

And finally, if the timeout is a setting (needed for performance use case for example) shouldn't the output of a timeout set by human hand be a valid json ?

Sorry for the long answer :/

Cheerz
PurpleBabar

**Comment by wfleming** [comment]
Hi, thanks for the answer, and apologies for how long it took us to think this over.

After discussion, we believe this is undesirable and are not going to implement this behavior. Timeouts are intended to catch runaway processes that could fail to ever terminate or could harm the system and other processes by consuming too many resources. A process that has reached a timeout is, in our opinion, in an unknown state and to any results we may have from should not be trusted. It also would make comparison between reports on different commits effectively impossible to do reliably, and that's a critical stability requirement for the product for us.

I do sympathize with your use case. codeclimate.com has features to help teams with these situations by [setting issue statuses](https://docs.codeclimate.com/docs/issues#section-issue-statuses) and making it easy to filter issues by severity & type, etc. to help teams chip away at technical debt without it needing to block current work. If you're focused on using the CLI, though, my suggestion would be to pick particular files or directories you want to improve & analyze only them (e.g. `codeclimate analyze app/models/user.rb`), then fix those files immediately.
