### ISSUE TITLE
Should the "console" command be exposed?

### ISSUE THREAD

**Issue by amochumber** [codeclimate/codeclimate#83]
If I run `codelimate help` my options list looks like so in version 0.2.8:

```
Available commands:
    analyze [-f format]
    console
    engines:disable engine_name
    engines:enable engine_name
    engines:install
    engines:list
    engines:remove engine_name
    help
    init
    validate-config
    version
```

If I run `codeclimate console` I get an interactive shell but it doesn't accept any of the normal codeclimate commands and I get this error:

```
NoMethodError: undefined method `engines' for #<CC::CLI::Console:0x007fd31dd2a800 @args=[]>
from (pry):1:in `run'
```

I've looked at the code in lib/cc/cli/console.rb (but since I'm not a ruby dev I'm not sure what I'm looking at) and it looks rather sparse.

So my question is should this command be available yet? Is it an impending feature that has made it to the wild? Or something else?

**Comment by GordonDiggs** [comment]
@amochumber The `console` command gives access to the classes within the CLI and is useful mostly for engine developers and maintainers. For example, to run analysis you would access the `Analyze` class directly: `CC::CLI::Analyze.new.run`
