### ISSUE TITLE
How can I get a value of maintainability ?

### ISSUE THREAD

**Issue by 2ur1st** [codeclimate/codeclimate#831]
Can I get a value of maintainability for my project ? 
I want to show all contributors which work with my project how good or bad it.

**Comment by wfleming** [comment]
Hi @2ur1st,

Right now maintainability ratings are only provided on [codeclimate.com](https://codeclimate.com), not as part of the CLI. Code Climate is free for Open Source projects, and if the project you're interested is closed source, you can sign up for your free trial. To get started you can go to https://codeclimate.com/quality/ and sign up with your github account.

**Comment by 2ur1st** [comment]
Hello @wfleming 
I  cant use codeclimate.com for my project, this project is close for any external service.
Do you plane to add maintainability ratings to CLI ? I think it`s very useful feature for most projects

**Comment by vovimayhem** [comment]
@2ur1st IMHO I don't think that is gonna make it to the CLI, since it's the project rating and the maintainability score the value proposition of codeclimate.com.
