### ISSUE TITLE
How pass code to container from pipe

### ISSUE THREAD

**Issue by 2ur1st** [codeclimate/codeclimate#833]
The documentation describe this feature:

> You can also pipe in source in combination with a path to analyze code that is not yet written to disk. 

If I right understand it should work like that:

```
echo '<?php echo "hello";' \
| docker run --env CODECLIMATE_CODE="$(pwd)" -v "$(pwd)":/code -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/cc:/tmp/cc codeclimate/codeclimate analyze app/AppKernel.php 
```
After run this command I get some issues about app/AppKernel.php file, 
but I want get issues about code from pipe

**How I can pass code to the codeclimate using pipe ?**

**Comment by maxjacobson** [comment]
Hi @2ur1st . I see you're invoking the docker image directly. The PR you pointed to, #645, implements most of the pipe logic in `codeclimate-wrapper`, a file that is outside of the docker image, and which is itself responsible for invoking the docker image correctly. If you follow the installation instructions in the readme, you should have a `codeclimate` binary installed, which runs the `codeclimate-wrapper` script.  Would you mind trying installing the binary and trying again?

**Comment by maxjacobson** [comment]
Hi @2ur1st. Right now we don't have that on our roadmap. The official way to use the CLI is via the wrapper script. For what it's worth, the script does use docker containers for the majority of the work, it just does a little setup first.
