### ISSUE TITLE
Integration codeclimate with IDE

### ISSUE THREAD

**Issue by 2ur1st** [codeclimate/codeclimate#837]
Hi, there.

I don not found a solution for integration the codeclimate with IDE. 
It cool have issues on CI pipe line, but may be to prevent code smells on development stage.

Did anyone integration the codeclimate with IDE ?

**Comment by davehenton** [comment]
Hey @2ur1st , happy to help with this. We have a few editor integrations which you might find helpful: 

- [Atom](https://docs.codeclimate.com/docs/code-climate-atom-package)
- [Vim](https://docs.codeclimate.com/docs/vim-plugin)
- [Sublime](https://github.com/codeclimate/SublimeLinter-contrib-codeclimate)

Let me know if you have any questions about those, or if there's anything else I can do for you on my end. Cheers.

**Comment by 2ur1st** [comment]
Hello @davehenton. Thank you. I want use the codeclimate in Jetbrains product ( PhpStorm )
I don not found plugin for this IDE, but may be are you know who did plugin for this tool ?

**Comment by DiegoRBaquero** [comment]
I would love to have integration with WebStorm!
