### ISSUE TITLE
Is RuboCop 0.58.2 available?

### ISSUE THREAD

**Issue by koic** [codeclimate/codeclimate#858]
First of all, thanks for such a useful service.

RuboCop 0.58.2 and Parser 2.5.1.2 have been released.

AFAIK, the `rubocop-0-58` channel has already been added, and seems to be tagged v0.76.0.
https://github.com/codeclimate/codeclimate/pull/855
https://github.com/codeclimate/codeclimate/releases/tag/v0.76.0

However, I confirmed that issues fixed in RuboCop 0.58.2 and Parser 2.5.1.2 is occurring in codeclimate.com. 

- Issue solved with RuboCop 0.58.2 (`Use 2 (not -2) spaces for indentation`) ... rubocop-hq/rubocop#6103
- Issue solved with Parser 2.5.1.2 (`unexpected token kDO`) ... whitequark/parser#520

Specifically, issues with `Use 2 (not -2) spaces for indentation` and `unexpected token kDO` occurred in rails/rails#33278. RuboCop 0.58.2 and Parser 2.5.1.2 will not find offenses locally. And the result at codeclimate.com is below.
https://codeclimate.com/github/rails/rails/pull/33278

I'd like to know two things.

1. Is there something I'm misunderstanding, is RuboCop 0.58.2 and Parser 2.5.1.2 available in codeclimate.com?
2. Is there a way for me to know the version of RuboCop and Parser that codeclimate.com is deployed?

Thank you.

**Comment by maxjacobson** [comment]
Hi @koic 

Thanks for the detailed issue. To see the list of rubocop release channels, you can look at the branches available on that repository: https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=%E2%9C%93&query=channel%2Frubocop

It appears that as of right now, the [`channel/rubocop-058` branch](https://github.com/codeclimate/codeclimate-rubocop/tree/channel/rubocop-0-58) is locked to 0.58.0. We can update that branch, do a little QA, and push that to users of that channel. I'll aim to do that today.

**Comment by koic** [comment]
@maxjacobson Thank you for your quick answer.
I could get to know where I could find out about the version of RuboCop and Parser supported by codeclimate.com. I also thank you for the early solution.

**Comment by koic** [comment]
I confirmed that it was upgraded to RuboCop 0.58.2. I appreciate your kindness.
