### ISSUE TITLE
Flog engine using old ruby_parser that doesn't support Ruby 2.3 syntax

### ISSUE THREAD

**Issue by cgriego** [codeclimate/codeclimate#860]
Code Climate's flog engine is using ruby_parser-3.8.4 but that version of ruby_parser doesn't support the <<~ Ruby 2.3 syntax for herdocs. ruby_parser 3.10.0 has added support and is released.

I'm reporting this here because I reported it to customer support originally over a year ago and they directed me to GitHub then and the issue still isn't fixed. The issue isn't really with the engine, the engine just needs to be rebuilt on the platform with the latest dependencies baked in.

Zendesk ticket #24280 for reference.

**Comment by andyw8** [comment]
I'm also running lots of parsing problems due to the old version of ruby-parser.

**Comment by cgriego** [comment]
Ruby 2.3 was released Dec 2015 and will hit _end of life_ in April of 2019.

**Comment by wfleming** [comment]
This would be more appropriate to track and try to address over at https://github.com/zenspider/codeclimate-flog, where this plugin is maintained.

**Comment by cgriego** [comment]
Did that a year ago prior to this issue being opened, but there’s no code change needed to the engine, the container just needs to be rebuilt.

https://github.com/zenspider/codeclimate-flog/issues/8

**Comment by zenspider** [comment]
I just commented on the original. This isn't up to me (afaik) and needs to be handled on CC's side. Correct me if I misunderstand the situation.

**Comment by maxjacobson** [comment]
That's right: let's track this via the issue on the plugin's repository: https://github.com/zenspider/codeclimate-flog/issues/8. Feel free to click "subscribe" on that one to be aware of updates.

I'll spend some time this week getting that update out. Thanks for the reminder.
