### ISSUE TITLE
Code Climate Coverage Failing

### ISSUE THREAD

**Issue by developer239** [codeclimate/codeclimate#862]
<img width="1190" alt="screen shot 2018-08-24 at 11 43 49" src="https://user-images.githubusercontent.com/14946081/44578642-7aada980-a794-11e8-9cbd-87f5d5142af9.png">

My project is on github if you need more details.

`.circleci/config.yml`: https://github.com/developer239/localized-graphql-koa-typescript/blob/master/.circleci/config.yml

I feel like this has something to do with my jest command: `node_modules/.bin/jest -i --forceExit --detectOpenHandles`

I have basically the same setup here: https://github.com/developer239/react-apollo-graphql/blob/master/.circleci/config.yml and it works fine. The only difference is that this is a backend project that has integration tests connected to the database. 

I would really appreciate any help. 🙂

**Comment by developer239** [comment]
There was a problem in jest config. Probably because I updated it to the latest version: https://github.com/developer239/localized-graphql-koa-typescript/commit/96d65bd6be560bb174f8bf957a578db6fda602cd#diff-2d0cd5d10b9604941c38c6aac608178aR28

**Comment by wfleming** [comment]
Glad you resolved this, FWIW if you have other test-reporter issues in the future, the https://github.com/codeclimate/test-reporter repo would be a better place to file issues than this repo, which is for our CLI.
