### ISSUE TITLE
Pylint engine missing from the manifest

### ISSUE THREAD

**Issue by vovimayhem** [codeclimate/codeclimate#886]
Given that [the pylint engine is documented on codeclimate.com](https://docs.codeclimate.com/docs/pylint), it's a bit confusing that the engine is actually missing from the available engines.

As [several of the engines in the beta channel were promoted to a stable channel](
https://github.com/codeclimate/codeclimate/pull/870#issuecomment-448020562) on [PR 870](https://github.com/codeclimate/codeclimate/pull/870) , the Pylint engine wasn't promoted at all.

Is there any way to include the Pylint engine to the stable channel?

**Comment by maxdanilov** [comment]
Hey, any updates for this issue? I believe it's not possible to use the `pylint` engine at all, even when specifying `channel: "beta"` in the config:

```bash
$ CODECLIMATE_DEBUG=1 codeclimate analyze
Starting analysis
I, [2020-01-03T18:15:48.771262 #1]  INFO -- : finished engine pylint
W, [2020-01-03T18:15:48.771344 #1]  WARN -- : skipped engine pylint: No engine named pylint found
Skipped pylint: No engine named pylint found

Analysis complete! Found 0 issues.
```
Codeclimate version: 0.85.6

**Comment by efueger** [comment]
Hi @maxdanilov - thanks for the bump! Checking into this.

**Comment by efueger** [comment]
Hi @maxdanilov - [Pylint now has a stable channel](https://github.com/codeclimate/codeclimate/commit/743634d356ff21aa90dd97664a3054c3e6a37295) on the CLI. Thanks again for the nudge!
