### ISSUE TITLE
Failure to install CLI on macOS

### ISSUE THREAD

**Issue by jasonkarns** [codeclimate/codeclimate#887]
- Include the exact command you're running and its complete output

`brew tap codeclimate/formulae` and `brew install codeclimate` were successful.

After that:

```
$ codeclimate --help
docker: Error response from daemon: Mounts denied: 
The path /usr/local/cache/codeclimate/cache.yml
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERRO[0000] error waiting for container: context canceled
```

  Include the output of the following commands:

  ```
  $ uname -a
Darwin FatJack-4.local 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64

$  docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true

$ env | grep "^DOCKER_"
DOCKER_CONFIG=/Users/jasonkarns/.config/docker
```

**Comment by filipesperandio** [comment]
Hey @jasonkarns !

Do you happen to have a `XDG_CACHE_HOME` or `CODECLIMATE_CACHE` env var set? Those would override the default cache directory under `$HOME/.cache`.
Docker-for-mac has a limitation of where volumes can be placed, being it within `$HOME` should be enough, but not outside.

**Comment by jasonkarns** [comment]
I do:

```
echo $XDG_CACHE_HOME 
/usr/local/cache
```

I'm confused, though. If the variable is set, why would that break this? Shouldn't it just use that directory as specified? And even if it doesn't, it's a _cache_ directory. Presence shouldn't be relied upon for operation, right? Regardless... what's the recommended workaround?

**Comment by filipesperandio** [comment]
Our CLI runs on docker and docker-for-mac has this limitation where it can't access directories outside  of users' home dir.
While it is not a problem on Linux, where it would simply use that path, on MacOS docker will error out with the message you saw.

You can `export CODECLIMATE_CACHE=$HOME/.cache` on your `.bash_profile` (or equivalent), that will override the cache dir only for the CLI.

As a simple test, you can invoke the CLI with that var set:
```shell
$ CODECLIMATE_CACHE=$HOME/.cache codeclimate --help
Usage: codeclimate COMMAND ...

Available commands:
    analyze [-f format] [-e engine[:channel]] [path]    Run analysis with the given arguments
    console                                             Open a ruby console for the CLI. Useful for developing against the CLI.
    engines:install                                     Pull the latest images for enabled engines in your configuration
    engines:list                                        List all available engines
    help [command]                                      Display help information.
    prepare [--allow-internal-ips]                      Run the commands in your prepare step.
    validate-config                                     Validate your .codeclimate.yml or .codeclimate.json.
    version                                             Display the CLI version.
```

**Comment by jasonkarns** [comment]
I can't find any existing issue about this under the docker org. Is it known? How should I be able to reproduce this in a way that pin points docker instead of codeclimate, such that I can open an issue to docker?

**Comment by jasonkarns** [comment]
(confirmed that using the env var as you mentioned works)

**Comment by filipesperandio** [comment]
Its a known limitation of `docker-for-mac`.

Reading this https://docs.docker.com/docker-for-mac/#file-sharing made me believe you could also add `/usr/local` to the shared directories and make it accessible.

**Comment by jasonkarns** [comment]
Thanks!

**Comment by jasonkarns** [comment]
FWIW, if anyone else runs into this, you have to add `/usr/local/cache` to the file sharing list. Attempting to add `/usr/local` gives _another_ error that usr/local is reserved by Docker. 🤦‍♂️
