### ISSUE TITLE
Freeze all strings

### ISSUE THREAD

**Issue by matteeyah** [codeclimate/codeclimate#904]
Moving forward `codeclimate` should probably slowly and iteratively enable the `# frozen_string_literal: true` magic comment throughout the source files. There's currently several uses of strings in a mutable way.

After this is done, the `Style/FrozenStringLiteralComment` cop should be enabled.

**Comment by filipesperandio** [comment]
Closing this one out, for now.
Explaning here: https://github.com/codeclimate/codeclimate/pull/988#issuecomment-818984866
I stil think it is a good idea, just want to do it in a way that it is less risky.
