### ISSUE TITLE
Javascript parser nullish coalescing and optional chaining support

### ISSUE THREAD

**Issue by M-TGH** [codeclimate/codeclimate#913]
_Wasn't entirely sure where to report this, it's specific to the javascript parser used by the structure and duplication engines. Feel free to transfer this issue to a more appropriate repository._

## Intro

We've been using CodeClimate for a bit with our large javascript codebase and noticed the engines were throwing some parser errors:

```
W, [2019-05-14T07:01:09.209216 #1]  WARN -- : Response status: 422
W, [2019-05-14T07:01:09.457129 #1]  WARN -- : Skipping path/to/file.js due to CC::Parser::Client::HTTPError
```

After diving into this by running codeclimate in debugging mode we noticed parseErrors pointing to places of code where nullish coalescing and/or optional chaining was being used. These are new proposals however already currently (experimentally) available through babel.

For more information on the two:

- Optional Chaining: [tc39/proposal-optional-chaining](https://github.com/tc39/proposal-optional-chaining)
- Nullish Coalescing: [tc39/proposal-nullish-coalescing](https://github.com/tc39/proposal-nullish-coalescing)

## The Issue

<details>
<summary>Running environment</summary>

```
Darwin MacBook-Pro-C02V61PTHV2Q.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```
</details>

### Optional Chaining

Running code climate over code including optional chaining operators will currently mark the file as having 0 issues and log a parseError when in debugging mode.

I've included some basic reproduction files and code climate output in a gist:
https://gist.github.com/M-TGH/9218e57f0cf2ab2224d33e65fe8db768

Note: These files do actually have 0 issues. However it would still report 0 issues if they did have issues.

### Nullish Coalescing

Running code climate over code including nullish coalescing operators will currently mark the file as having 0 issues and log a parseError when in debugging mode.

I've included some basic reproduction files and code climate output in a gist:
https://gist.github.com/M-TGH/bc6aa9db78c1987add93ff85f4a003ea

## Conclusion/Proposal

Supporting these operators in the javascript parser would be a nice to have feature. As far as I am aware these proposals both aren't very likely to change syntax anymore. So whilst they are in relatively early stages, it's safe to assume this syntax will be the one that stays going forward.

**Comment by wouterb** [comment]
The codeclimate javascript parser seems to use [babylon 6.18.0](https://www.npmjs.com/package/babylon) to parse the code. 
To support Optional Chaining ([@babel/plugin-proposal-optional-chaining](https://www.npmjs.com/package/@babel/plugin-proposal-optional-chaining)) and Nullish Coalescing ([@babel/plugin-proposal-nullish-coalescing-operator](https://www.npmjs.com/package/@babel/plugin-proposal-nullish-coalescing-operator)) [@babel/parser >7](https://www.npmjs.com/package/@babel/parser) is required.

**Comment by efueger** [comment]
Thanks for your patience and the heads up @M-TGH ! Checking with our dev team on this. 👌

**Comment by efueger** [comment]
Thanks for your patience! We've updated the parser and no longer see the parser errors on our sample repo.

Let me know if you have any other problems with this 👌
