### ISSUE TITLE
Add Engine for SCSS-Lint?

### ISSUE THREAD

**Issue by elwayman02** [codeclimate/codeclimate#92]
Are there any plans to add scss-lint to the engines list? csslint isn't really all that helpful as an engine in the days of LESS & SASS...it just throws a bunch of useless errors for most projects.

**Comment by GordonDiggs** [comment]
@elwayman02 We do have plans to add it! It's not quite ready yet but I will update this issue when we release it

**Comment by elwayman02** [comment]
Thanks @GordonDiggs!

**Comment by dylangrafmyre** [comment]
:+1: 
The maintainer of scss-lint also has slim-lint and haml-lint. Maybe you can add 3 for the price of one :)

**Comment by GordonDiggs** [comment]
@elwayman02 @dylangrafmyre 

SCSS Lint is now available as of version 0.6.0! To enable it, you can run `codeclimate engines:enable scss-lint`

**Comment by elwayman02** [comment]
Awesome, glad to hear it!

**Comment by dylangrafmyre** [comment]
Great! Thank You!

**Comment by aliceinwire** [comment]
:+1
