### ISSUE TITLE
[Feature Request] Code Climate JetBrains plugin

### ISSUE THREAD

**Issue by kaushalyap** [codeclimate/codeclimate#927]
Hi there!

Currently there is no official code climate plugin for JetBrains IDEs. Having a plugin allows to fix issues at development phase.

there is [similar old issue](https://github.com/codeclimate/codeclimate/issues/837) but it was closed without proper response.

**Comment by nhat-phan** [comment]
@kaushalyap Here you go: https://plugins.jetbrains.com/plugin/13306-code-cleaner-with-code-climate-cli/

**Comment by kaushalyap** [comment]
Thanks.
