### ISSUE TITLE
When I try the curl command mentioned in the README, it returns "Not Found."

### ISSUE THREAD

**Issue by dvjensen17** [codeclimate/codeclimate#967]
Hi there!

I hope this is not a silly mistake on my part, but it is blocking me nonetheless so here goes.

When I try to use the curl command mentioned in the README to download the project, the curl command returns "Not Found."

This is what I did in a terminal window:

curl -L https://github.com/codeclimate/archive/master.tar.gz

That command immediately returned:

Not Found

I am running Ubuntu 18.04.4 LTS

**Comment by efueger** [comment]
Hi there 👋 

Can you try adding an extra /codeclimate/ in the url?

- `curl -L https://github.com/codeclimate/codeclimate/archive/master.tar.gz`


Cheers,
Emily

**Comment by dvjensen17** [comment]
Yes, thank you. You are right. I missed that. Sorry!
